// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class _GtkTreeModelFilterClass {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            MemoryLayout.structLayout(
                Constants$root.C_LONG_LONG$LAYOUT.withName("g_type")
            ).withName("g_type_class"),
            Constants$root.C_POINTER$LAYOUT.withName("construct_properties"),
            Constants$root.C_POINTER$LAYOUT.withName("constructor"),
            Constants$root.C_POINTER$LAYOUT.withName("set_property"),
            Constants$root.C_POINTER$LAYOUT.withName("get_property"),
            Constants$root.C_POINTER$LAYOUT.withName("dispose"),
            Constants$root.C_POINTER$LAYOUT.withName("finalize"),
            Constants$root.C_POINTER$LAYOUT.withName("dispatch_properties_changed"),
            Constants$root.C_POINTER$LAYOUT.withName("notify"),
            Constants$root.C_POINTER$LAYOUT.withName("constructed"),
            Constants$root.C_LONG_LONG$LAYOUT.withName("flags"),
            MemoryLayout.sequenceLayout(6, Constants$root.C_POINTER$LAYOUT).withName("pdummy")
        ).withName("parent_class"),
        Constants$root.C_POINTER$LAYOUT.withName("visible"),
        Constants$root.C_POINTER$LAYOUT.withName("modify"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_POINTER$LAYOUT).withName("padding")
    ).withName("_GtkTreeModelFilterClass");
    public static MemoryLayout $LAYOUT() {
        return _GtkTreeModelFilterClass.$struct$LAYOUT;
    }
    public static MemorySegment parent_class$slice(MemorySegment seg) {
        return seg.asSlice(0, 136);
    }
    static final FunctionDescriptor visible$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle visible$MH = RuntimeHelper.downcallHandle(
        _GtkTreeModelFilterClass.visible$FUNC
    );
    public interface visible {

        int apply(java.lang.foreign.MemoryAddress _x0, java.lang.foreign.MemoryAddress _x1, java.lang.foreign.MemoryAddress _x2);
        static MemorySegment allocate(visible fi, MemorySession session) {
            return RuntimeHelper.upcallStub(visible.class, fi, _GtkTreeModelFilterClass.visible$FUNC, session);
        }
        static visible ofAddress(MemoryAddress addr, MemorySession session) {
            MemorySegment symbol = MemorySegment.ofAddress(addr, 0, session);
            return (java.lang.foreign.MemoryAddress __x0, java.lang.foreign.MemoryAddress __x1, java.lang.foreign.MemoryAddress __x2) -> {
                try {
                    return (int)_GtkTreeModelFilterClass.visible$MH.invokeExact((Addressable)symbol, (java.lang.foreign.Addressable)__x0, (java.lang.foreign.Addressable)__x1, (java.lang.foreign.Addressable)__x2);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle visible$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("visible"));
    public static VarHandle visible$VH() {
        return _GtkTreeModelFilterClass.visible$VH;
    }
    public static MemoryAddress visible$get(MemorySegment seg) {
        return (java.lang.foreign.MemoryAddress)_GtkTreeModelFilterClass.visible$VH.get(seg);
    }
    public static void visible$set( MemorySegment seg, MemoryAddress x) {
        _GtkTreeModelFilterClass.visible$VH.set(seg, x);
    }
    public static MemoryAddress visible$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemoryAddress)_GtkTreeModelFilterClass.visible$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void visible$set(MemorySegment seg, long index, MemoryAddress x) {
        _GtkTreeModelFilterClass.visible$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static visible visible (MemorySegment segment, MemorySession session) {
        return visible.ofAddress(visible$get(segment), session);
    }
    static final FunctionDescriptor modify$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle modify$MH = RuntimeHelper.downcallHandle(
        _GtkTreeModelFilterClass.modify$FUNC
    );
    public interface modify {

        void apply(java.lang.foreign.MemoryAddress _x0, java.lang.foreign.MemoryAddress _x1, java.lang.foreign.MemoryAddress _x2, java.lang.foreign.MemoryAddress _x3, int _x4);
        static MemorySegment allocate(modify fi, MemorySession session) {
            return RuntimeHelper.upcallStub(modify.class, fi, _GtkTreeModelFilterClass.modify$FUNC, session);
        }
        static modify ofAddress(MemoryAddress addr, MemorySession session) {
            MemorySegment symbol = MemorySegment.ofAddress(addr, 0, session);
            return (java.lang.foreign.MemoryAddress __x0, java.lang.foreign.MemoryAddress __x1, java.lang.foreign.MemoryAddress __x2, java.lang.foreign.MemoryAddress __x3, int __x4) -> {
                try {
                    _GtkTreeModelFilterClass.modify$MH.invokeExact((Addressable)symbol, (java.lang.foreign.Addressable)__x0, (java.lang.foreign.Addressable)__x1, (java.lang.foreign.Addressable)__x2, (java.lang.foreign.Addressable)__x3, __x4);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle modify$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("modify"));
    public static VarHandle modify$VH() {
        return _GtkTreeModelFilterClass.modify$VH;
    }
    public static MemoryAddress modify$get(MemorySegment seg) {
        return (java.lang.foreign.MemoryAddress)_GtkTreeModelFilterClass.modify$VH.get(seg);
    }
    public static void modify$set( MemorySegment seg, MemoryAddress x) {
        _GtkTreeModelFilterClass.modify$VH.set(seg, x);
    }
    public static MemoryAddress modify$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemoryAddress)_GtkTreeModelFilterClass.modify$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void modify$set(MemorySegment seg, long index, MemoryAddress x) {
        _GtkTreeModelFilterClass.modify$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static modify modify (MemorySegment segment, MemorySession session) {
        return modify.ofAddress(modify$get(segment), session);
    }
    public static MemorySegment padding$slice(MemorySegment seg) {
        return seg.asSlice(152, 64);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


