// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2298 {

    static final FunctionDescriptor gtk_print_operation_get_embed_page_setup$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_print_operation_get_embed_page_setup$MH = RuntimeHelper.downcallHandle(
        "gtk_print_operation_get_embed_page_setup",
        constants$2298.gtk_print_operation_get_embed_page_setup$FUNC
    );
    static final FunctionDescriptor gtk_print_operation_get_n_pages_to_print$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_print_operation_get_n_pages_to_print$MH = RuntimeHelper.downcallHandle(
        "gtk_print_operation_get_n_pages_to_print",
        constants$2298.gtk_print_operation_get_n_pages_to_print$FUNC
    );
    static final FunctionDescriptor gtk_print_run_page_setup_dialog$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_print_run_page_setup_dialog$MH = RuntimeHelper.downcallHandle(
        "gtk_print_run_page_setup_dialog",
        constants$2298.gtk_print_run_page_setup_dialog$FUNC
    );
    static final FunctionDescriptor GtkPageSetupDoneFunc$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GtkPageSetupDoneFunc$MH = RuntimeHelper.downcallHandle(
        constants$2298.GtkPageSetupDoneFunc$FUNC
    );
    static final FunctionDescriptor gtk_print_run_page_setup_dialog_async$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_print_run_page_setup_dialog_async$MH = RuntimeHelper.downcallHandle(
        "gtk_print_run_page_setup_dialog_async",
        constants$2298.gtk_print_run_page_setup_dialog_async$FUNC
    );
}


