// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2785 {

    static final FunctionDescriptor ADW_IS_PREFERENCES_PAGE$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ADW_IS_PREFERENCES_PAGE$MH = RuntimeHelper.downcallHandle(
        "ADW_IS_PREFERENCES_PAGE",
        constants$2785.ADW_IS_PREFERENCES_PAGE$FUNC
    );
    static final FunctionDescriptor ADW_IS_PREFERENCES_PAGE_CLASS$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ADW_IS_PREFERENCES_PAGE_CLASS$MH = RuntimeHelper.downcallHandle(
        "ADW_IS_PREFERENCES_PAGE_CLASS",
        constants$2785.ADW_IS_PREFERENCES_PAGE_CLASS$FUNC
    );
    static final FunctionDescriptor ADW_PREFERENCES_PAGE_GET_CLASS$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ADW_PREFERENCES_PAGE_GET_CLASS$MH = RuntimeHelper.downcallHandle(
        "ADW_PREFERENCES_PAGE_GET_CLASS",
        constants$2785.ADW_PREFERENCES_PAGE_GET_CLASS$FUNC
    );
    static final FunctionDescriptor adw_preferences_page_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle adw_preferences_page_new$MH = RuntimeHelper.downcallHandle(
        "adw_preferences_page_new",
        constants$2785.adw_preferences_page_new$FUNC
    );
    static final FunctionDescriptor adw_preferences_page_get_icon_name$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle adw_preferences_page_get_icon_name$MH = RuntimeHelper.downcallHandle(
        "adw_preferences_page_get_icon_name",
        constants$2785.adw_preferences_page_get_icon_name$FUNC
    );
    static final FunctionDescriptor adw_preferences_page_set_icon_name$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle adw_preferences_page_set_icon_name$MH = RuntimeHelper.downcallHandle(
        "adw_preferences_page_set_icon_name",
        constants$2785.adw_preferences_page_set_icon_name$FUNC
    );
}


