// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2129 {

    static final FunctionDescriptor glib_autoptr_clear_GtkGridLayoutChildClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GtkGridLayoutChildClass$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GtkGridLayoutChildClass",
        constants$2129.glib_autoptr_clear_GtkGridLayoutChildClass$FUNC
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GtkGridLayoutChildClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GtkGridLayoutChildClass$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GtkGridLayoutChildClass",
        constants$2129.glib_autoptr_cleanup_GtkGridLayoutChildClass$FUNC
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GtkGridLayoutChildClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GtkGridLayoutChildClass$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GtkGridLayoutChildClass",
        constants$2129.glib_listautoptr_cleanup_GtkGridLayoutChildClass$FUNC
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GtkGridLayoutChildClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GtkGridLayoutChildClass$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GtkGridLayoutChildClass",
        constants$2129.glib_slistautoptr_cleanup_GtkGridLayoutChildClass$FUNC
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GtkGridLayoutChildClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GtkGridLayoutChildClass$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GtkGridLayoutChildClass",
        constants$2129.glib_queueautoptr_cleanup_GtkGridLayoutChildClass$FUNC
    );
    static final FunctionDescriptor GTK_GRID_LAYOUT_CHILD$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GTK_GRID_LAYOUT_CHILD$MH = RuntimeHelper.downcallHandle(
        "GTK_GRID_LAYOUT_CHILD",
        constants$2129.GTK_GRID_LAYOUT_CHILD$FUNC
    );
}


