// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2792 {

    static final FunctionDescriptor adw_toast_dismiss$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle adw_toast_dismiss$MH = RuntimeHelper.downcallHandle(
        "adw_toast_dismiss",
        constants$2792.adw_toast_dismiss$FUNC
    );
    static final FunctionDescriptor adw_window_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle adw_window_get_type$MH = RuntimeHelper.downcallHandle(
        "adw_window_get_type",
        constants$2792.adw_window_get_type$FUNC
    );
    static final FunctionDescriptor glib_autoptr_clear_AdwWindow$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_AdwWindow$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_AdwWindow",
        constants$2792.glib_autoptr_clear_AdwWindow$FUNC
    );
    static final FunctionDescriptor glib_autoptr_cleanup_AdwWindow$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_AdwWindow$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_AdwWindow",
        constants$2792.glib_autoptr_cleanup_AdwWindow$FUNC
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_AdwWindow$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_AdwWindow$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_AdwWindow",
        constants$2792.glib_listautoptr_cleanup_AdwWindow$FUNC
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_AdwWindow$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_AdwWindow$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_AdwWindow",
        constants$2792.glib_slistautoptr_cleanup_AdwWindow$FUNC
    );
}


