// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1543 {

    static final FunctionDescriptor __tanhf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __tanhf$MH = RuntimeHelper.downcallHandle(
        "__tanhf",
        constants$1543.__tanhf$FUNC
    );
    static final FunctionDescriptor acoshf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle acoshf$MH = RuntimeHelper.downcallHandle(
        "acoshf",
        constants$1543.acoshf$FUNC
    );
    static final FunctionDescriptor __acoshf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __acoshf$MH = RuntimeHelper.downcallHandle(
        "__acoshf",
        constants$1543.__acoshf$FUNC
    );
    static final FunctionDescriptor asinhf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle asinhf$MH = RuntimeHelper.downcallHandle(
        "asinhf",
        constants$1543.asinhf$FUNC
    );
    static final FunctionDescriptor __asinhf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __asinhf$MH = RuntimeHelper.downcallHandle(
        "__asinhf",
        constants$1543.__asinhf$FUNC
    );
    static final FunctionDescriptor atanhf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle atanhf$MH = RuntimeHelper.downcallHandle(
        "atanhf",
        constants$1543.atanhf$FUNC
    );
}


