// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2266 {

    static final FunctionDescriptor gtk_paned_set_wide_handle$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_paned_set_wide_handle$MH = RuntimeHelper.downcallHandle(
        "gtk_paned_set_wide_handle",
        constants$2266.gtk_paned_set_wide_handle$FUNC
    );
    static final FunctionDescriptor gtk_paned_get_wide_handle$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_paned_get_wide_handle$MH = RuntimeHelper.downcallHandle(
        "gtk_paned_get_wide_handle",
        constants$2266.gtk_paned_get_wide_handle$FUNC
    );
    static final FunctionDescriptor gtk_password_entry_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_password_entry_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_password_entry_get_type",
        constants$2266.gtk_password_entry_get_type$FUNC
    );
    static final FunctionDescriptor gtk_password_entry_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle gtk_password_entry_new$MH = RuntimeHelper.downcallHandle(
        "gtk_password_entry_new",
        constants$2266.gtk_password_entry_new$FUNC
    );
    static final FunctionDescriptor gtk_password_entry_set_show_peek_icon$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_password_entry_set_show_peek_icon$MH = RuntimeHelper.downcallHandle(
        "gtk_password_entry_set_show_peek_icon",
        constants$2266.gtk_password_entry_set_show_peek_icon$FUNC
    );
    static final FunctionDescriptor gtk_password_entry_get_show_peek_icon$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_password_entry_get_show_peek_icon$MH = RuntimeHelper.downcallHandle(
        "gtk_password_entry_get_show_peek_icon",
        constants$2266.gtk_password_entry_get_show_peek_icon$FUNC
    );
}


