// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1519 {

    static final FunctionDescriptor __tanh$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __tanh$MH = RuntimeHelper.downcallHandle(
        "__tanh",
        constants$1519.__tanh$FUNC
    );
    static final FunctionDescriptor acosh$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle acosh$MH = RuntimeHelper.downcallHandle(
        "acosh",
        constants$1519.acosh$FUNC
    );
    static final FunctionDescriptor __acosh$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __acosh$MH = RuntimeHelper.downcallHandle(
        "__acosh",
        constants$1519.__acosh$FUNC
    );
    static final FunctionDescriptor asinh$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle asinh$MH = RuntimeHelper.downcallHandle(
        "asinh",
        constants$1519.asinh$FUNC
    );
    static final FunctionDescriptor __asinh$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __asinh$MH = RuntimeHelper.downcallHandle(
        "__asinh",
        constants$1519.__asinh$FUNC
    );
    static final FunctionDescriptor atanh$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle atanh$MH = RuntimeHelper.downcallHandle(
        "atanh",
        constants$1519.atanh$FUNC
    );
}


