// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2059 {

    static final FunctionDescriptor gtk_expander_new_with_mnemonic$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_expander_new_with_mnemonic$MH = RuntimeHelper.downcallHandle(
        "gtk_expander_new_with_mnemonic",
        constants$2059.gtk_expander_new_with_mnemonic$FUNC
    );
    static final FunctionDescriptor gtk_expander_set_expanded$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_expander_set_expanded$MH = RuntimeHelper.downcallHandle(
        "gtk_expander_set_expanded",
        constants$2059.gtk_expander_set_expanded$FUNC
    );
    static final FunctionDescriptor gtk_expander_get_expanded$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_expander_get_expanded$MH = RuntimeHelper.downcallHandle(
        "gtk_expander_get_expanded",
        constants$2059.gtk_expander_get_expanded$FUNC
    );
    static final FunctionDescriptor gtk_expander_set_label$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_expander_set_label$MH = RuntimeHelper.downcallHandle(
        "gtk_expander_set_label",
        constants$2059.gtk_expander_set_label$FUNC
    );
    static final FunctionDescriptor gtk_expander_get_label$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_expander_get_label$MH = RuntimeHelper.downcallHandle(
        "gtk_expander_get_label",
        constants$2059.gtk_expander_get_label$FUNC
    );
    static final FunctionDescriptor gtk_expander_set_use_underline$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_expander_set_use_underline$MH = RuntimeHelper.downcallHandle(
        "gtk_expander_set_use_underline",
        constants$2059.gtk_expander_set_use_underline$FUNC
    );
}


