// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2884 {

    static final MemorySegment G_OS_INFO_KEY_PRIVACY_POLICY_URL$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("PRIVACY_POLICY_URL");
    static final MemoryAddress SIG_ERR$ADDR = MemoryAddress.ofLong(-1L);
    static final MemoryAddress SIG_DFL$ADDR = MemoryAddress.ofLong(0L);
    static final MemoryAddress SIG_IGN$ADDR = MemoryAddress.ofLong(1L);
    static final MemorySegment G_KEY_FILE_DESKTOP_GROUP$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("Desktop Entry");
    static final MemorySegment G_KEY_FILE_DESKTOP_KEY_TYPE$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("Type");
}


