// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2912 {

    static final MemorySegment NS_TSIG_ALG_HMAC_MD5$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("HMAC-MD5.SIG-ALG.REG.INT");
    static final MemorySegment _PATH_RESCONF$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("/etc/resolv.conf");
    static final MemorySegment CAIRO_VERSION_STRING$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("1.17.6");
    static final MemorySegment CAIRO_TAG_DEST$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("cairo.dest");
    static final MemorySegment CAIRO_TAG_LINK$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("Link");
    static final MemorySegment CAIRO_MIME_TYPE_JPEG$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("image/jpeg");
}


