// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1513 {

    static final FunctionDescriptor _mm_unpackhi_pd$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _mm_unpackhi_pd$MH = RuntimeHelper.downcallHandle(
        "_mm_unpackhi_pd",
        constants$1513._mm_unpackhi_pd$FUNC
    );
    static final FunctionDescriptor _mm_unpacklo_pd$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _mm_unpacklo_pd$MH = RuntimeHelper.downcallHandle(
        "_mm_unpacklo_pd",
        constants$1513._mm_unpacklo_pd$FUNC
    );
    static final FunctionDescriptor _mm_movemask_pd$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _mm_movemask_pd$MH = RuntimeHelper.downcallHandle(
        "_mm_movemask_pd",
        constants$1513._mm_movemask_pd$FUNC
    );
    static final FunctionDescriptor _mm_castpd_ps$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _mm_castpd_ps$MH = RuntimeHelper.downcallHandle(
        "_mm_castpd_ps",
        constants$1513._mm_castpd_ps$FUNC
    );
    static final FunctionDescriptor _mm_castpd_si128$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _mm_castpd_si128$MH = RuntimeHelper.downcallHandle(
        "_mm_castpd_si128",
        constants$1513._mm_castpd_si128$FUNC
    );
    static final FunctionDescriptor _mm_castps_pd$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _mm_castps_pd$MH = RuntimeHelper.downcallHandle(
        "_mm_castps_pd",
        constants$1513._mm_castps_pd$FUNC
    );
}


