// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2688 {

    static final FunctionDescriptor glib_autoptr_clear_AdwCallbackAnimationTargetClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_AdwCallbackAnimationTargetClass$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_AdwCallbackAnimationTargetClass",
        constants$2688.glib_autoptr_clear_AdwCallbackAnimationTargetClass$FUNC
    );
    static final FunctionDescriptor glib_autoptr_cleanup_AdwCallbackAnimationTargetClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_AdwCallbackAnimationTargetClass$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_AdwCallbackAnimationTargetClass",
        constants$2688.glib_autoptr_cleanup_AdwCallbackAnimationTargetClass$FUNC
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_AdwCallbackAnimationTargetClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_AdwCallbackAnimationTargetClass$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_AdwCallbackAnimationTargetClass",
        constants$2688.glib_listautoptr_cleanup_AdwCallbackAnimationTargetClass$FUNC
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_AdwCallbackAnimationTargetClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_AdwCallbackAnimationTargetClass$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_AdwCallbackAnimationTargetClass",
        constants$2688.glib_slistautoptr_cleanup_AdwCallbackAnimationTargetClass$FUNC
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_AdwCallbackAnimationTargetClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_AdwCallbackAnimationTargetClass$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_AdwCallbackAnimationTargetClass",
        constants$2688.glib_queueautoptr_cleanup_AdwCallbackAnimationTargetClass$FUNC
    );
    static final FunctionDescriptor ADW_CALLBACK_ANIMATION_TARGET$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ADW_CALLBACK_ANIMATION_TARGET$MH = RuntimeHelper.downcallHandle(
        "ADW_CALLBACK_ANIMATION_TARGET",
        constants$2688.ADW_CALLBACK_ANIMATION_TARGET$FUNC
    );
}


