// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2180 {

    static final FunctionDescriptor glib_listautoptr_cleanup_GtkListBoxRow$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GtkListBoxRow$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GtkListBoxRow",
        constants$2180.glib_listautoptr_cleanup_GtkListBoxRow$FUNC
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GtkListBoxRow$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GtkListBoxRow$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GtkListBoxRow",
        constants$2180.glib_slistautoptr_cleanup_GtkListBoxRow$FUNC
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GtkListBoxRow$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GtkListBoxRow$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GtkListBoxRow",
        constants$2180.glib_queueautoptr_cleanup_GtkListBoxRow$FUNC
    );
    static final FunctionDescriptor gtk_list_item_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_list_item_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_list_item_get_type",
        constants$2180.gtk_list_item_get_type$FUNC
    );
    static final FunctionDescriptor gtk_list_item_get_item$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_list_item_get_item$MH = RuntimeHelper.downcallHandle(
        "gtk_list_item_get_item",
        constants$2180.gtk_list_item_get_item$FUNC
    );
    static final FunctionDescriptor gtk_list_item_get_position$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_list_item_get_position$MH = RuntimeHelper.downcallHandle(
        "gtk_list_item_get_position",
        constants$2180.gtk_list_item_get_position$FUNC
    );
}


