// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1229 {

    static final FunctionDescriptor pango_color_parse$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_color_parse$MH = RuntimeHelper.downcallHandle(
        "pango_color_parse",
        constants$1229.pango_color_parse$FUNC
    );
    static final FunctionDescriptor pango_color_parse_with_alpha$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_color_parse_with_alpha$MH = RuntimeHelper.downcallHandle(
        "pango_color_parse_with_alpha",
        constants$1229.pango_color_parse_with_alpha$FUNC
    );
    static final FunctionDescriptor pango_color_to_string$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_color_to_string$MH = RuntimeHelper.downcallHandle(
        "pango_color_to_string",
        constants$1229.pango_color_to_string$FUNC
    );
    static final FunctionDescriptor PangoAttrFilterFunc$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PangoAttrFilterFunc$MH = RuntimeHelper.downcallHandle(
        constants$1229.PangoAttrFilterFunc$FUNC
    );
    static final FunctionDescriptor PangoAttrDataCopyFunc$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
}


