// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2865 {

    static final FunctionDescriptor adw_view_switcher_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle adw_view_switcher_get_type$MH = RuntimeHelper.downcallHandle(
        "adw_view_switcher_get_type",
        constants$2865.adw_view_switcher_get_type$FUNC
    );
    static final FunctionDescriptor glib_autoptr_clear_AdwViewSwitcher$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_AdwViewSwitcher$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_AdwViewSwitcher",
        constants$2865.glib_autoptr_clear_AdwViewSwitcher$FUNC
    );
    static final FunctionDescriptor glib_autoptr_cleanup_AdwViewSwitcher$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_AdwViewSwitcher$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_AdwViewSwitcher",
        constants$2865.glib_autoptr_cleanup_AdwViewSwitcher$FUNC
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_AdwViewSwitcher$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_AdwViewSwitcher$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_AdwViewSwitcher",
        constants$2865.glib_listautoptr_cleanup_AdwViewSwitcher$FUNC
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_AdwViewSwitcher$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_AdwViewSwitcher$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_AdwViewSwitcher",
        constants$2865.glib_slistautoptr_cleanup_AdwViewSwitcher$FUNC
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_AdwViewSwitcher$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_AdwViewSwitcher$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_AdwViewSwitcher",
        constants$2865.glib_queueautoptr_cleanup_AdwViewSwitcher$FUNC
    );
}


