// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2678 {

    static final FunctionDescriptor adw_preferences_row_set_title$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle adw_preferences_row_set_title$MH = RuntimeHelper.downcallHandle(
        "adw_preferences_row_set_title",
        constants$2678.adw_preferences_row_set_title$FUNC
    );
    static final FunctionDescriptor adw_preferences_row_get_use_underline$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle adw_preferences_row_get_use_underline$MH = RuntimeHelper.downcallHandle(
        "adw_preferences_row_get_use_underline",
        constants$2678.adw_preferences_row_get_use_underline$FUNC
    );
    static final FunctionDescriptor adw_preferences_row_set_use_underline$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle adw_preferences_row_set_use_underline$MH = RuntimeHelper.downcallHandle(
        "adw_preferences_row_set_use_underline",
        constants$2678.adw_preferences_row_set_use_underline$FUNC
    );
    static final FunctionDescriptor adw_preferences_row_get_title_selectable$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle adw_preferences_row_get_title_selectable$MH = RuntimeHelper.downcallHandle(
        "adw_preferences_row_get_title_selectable",
        constants$2678.adw_preferences_row_get_title_selectable$FUNC
    );
    static final FunctionDescriptor adw_preferences_row_set_title_selectable$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle adw_preferences_row_set_title_selectable$MH = RuntimeHelper.downcallHandle(
        "adw_preferences_row_set_title_selectable",
        constants$2678.adw_preferences_row_set_title_selectable$FUNC
    );
    static final FunctionDescriptor adw_action_row_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle adw_action_row_get_type$MH = RuntimeHelper.downcallHandle(
        "adw_action_row_get_type",
        constants$2678.adw_action_row_get_type$FUNC
    );
}


