// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2824 {

    static final FunctionDescriptor glib_queueautoptr_cleanup_AdwSwipeable$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_AdwSwipeable$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_AdwSwipeable",
        constants$2824.glib_queueautoptr_cleanup_AdwSwipeable$FUNC
    );
    static final FunctionDescriptor ADW_SWIPEABLE$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ADW_SWIPEABLE$MH = RuntimeHelper.downcallHandle(
        "ADW_SWIPEABLE",
        constants$2824.ADW_SWIPEABLE$FUNC
    );
    static final FunctionDescriptor ADW_IS_SWIPEABLE$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ADW_IS_SWIPEABLE$MH = RuntimeHelper.downcallHandle(
        "ADW_IS_SWIPEABLE",
        constants$2824.ADW_IS_SWIPEABLE$FUNC
    );
    static final FunctionDescriptor ADW_SWIPEABLE_GET_IFACE$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ADW_SWIPEABLE_GET_IFACE$MH = RuntimeHelper.downcallHandle(
        "ADW_SWIPEABLE_GET_IFACE",
        constants$2824.ADW_SWIPEABLE_GET_IFACE$FUNC
    );
    static final FunctionDescriptor adw_swipeable_get_distance$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle adw_swipeable_get_distance$MH = RuntimeHelper.downcallHandle(
        "adw_swipeable_get_distance",
        constants$2824.adw_swipeable_get_distance$FUNC
    );
    static final FunctionDescriptor adw_swipeable_get_snap_points$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle adw_swipeable_get_snap_points$MH = RuntimeHelper.downcallHandle(
        "adw_swipeable_get_snap_points",
        constants$2824.adw_swipeable_get_snap_points$FUNC
    );
}


