// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1613 {

    static final FunctionDescriptor graphene_rect_round_to_pixel$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_rect_round_to_pixel$MH = RuntimeHelper.downcallHandle(
        "graphene_rect_round_to_pixel",
        constants$1613.graphene_rect_round_to_pixel$FUNC
    );
    static final FunctionDescriptor graphene_rect_round$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_rect_round$MH = RuntimeHelper.downcallHandle(
        "graphene_rect_round",
        constants$1613.graphene_rect_round$FUNC
    );
    static final FunctionDescriptor graphene_rect_round_extents$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_rect_round_extents$MH = RuntimeHelper.downcallHandle(
        "graphene_rect_round_extents",
        constants$1613.graphene_rect_round_extents$FUNC
    );
    static final FunctionDescriptor graphene_rect_interpolate$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_rect_interpolate$MH = RuntimeHelper.downcallHandle(
        "graphene_rect_interpolate",
        constants$1613.graphene_rect_interpolate$FUNC
    );
    static final FunctionDescriptor graphene_rect_expand$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_rect_expand$MH = RuntimeHelper.downcallHandle(
        "graphene_rect_expand",
        constants$1613.graphene_rect_expand$FUNC
    );
    static final FunctionDescriptor graphene_rect_zero$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle graphene_rect_zero$MH = RuntimeHelper.downcallHandle(
        "graphene_rect_zero",
        constants$1613.graphene_rect_zero$FUNC
    );
}


