// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2514 {

    static final FunctionDescriptor glib_autoptr_clear_GtkCalendar$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GtkCalendar$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GtkCalendar",
        constants$2514.glib_autoptr_clear_GtkCalendar$FUNC
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GtkCalendar$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GtkCalendar$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GtkCalendar",
        constants$2514.glib_autoptr_cleanup_GtkCalendar$FUNC
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GtkCalendar$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GtkCalendar$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GtkCalendar",
        constants$2514.glib_listautoptr_cleanup_GtkCalendar$FUNC
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GtkCalendar$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GtkCalendar$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GtkCalendar",
        constants$2514.glib_slistautoptr_cleanup_GtkCalendar$FUNC
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GtkCalendar$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GtkCalendar$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GtkCalendar",
        constants$2514.glib_queueautoptr_cleanup_GtkCalendar$FUNC
    );
    static final FunctionDescriptor glib_autoptr_clear_GtkCellArea$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GtkCellArea$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GtkCellArea",
        constants$2514.glib_autoptr_clear_GtkCellArea$FUNC
    );
}


