// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2027 {

    static final FunctionDescriptor glib_slistautoptr_cleanup_GtkCustomLayoutClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GtkCustomLayoutClass$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GtkCustomLayoutClass",
        constants$2027.glib_slistautoptr_cleanup_GtkCustomLayoutClass$FUNC
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GtkCustomLayoutClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GtkCustomLayoutClass$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GtkCustomLayoutClass",
        constants$2027.glib_queueautoptr_cleanup_GtkCustomLayoutClass$FUNC
    );
    static final FunctionDescriptor GTK_CUSTOM_LAYOUT$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GTK_CUSTOM_LAYOUT$MH = RuntimeHelper.downcallHandle(
        "GTK_CUSTOM_LAYOUT",
        constants$2027.GTK_CUSTOM_LAYOUT$FUNC
    );
    static final FunctionDescriptor GTK_IS_CUSTOM_LAYOUT$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GTK_IS_CUSTOM_LAYOUT$MH = RuntimeHelper.downcallHandle(
        "GTK_IS_CUSTOM_LAYOUT",
        constants$2027.GTK_IS_CUSTOM_LAYOUT$FUNC
    );
    static final FunctionDescriptor gtk_custom_layout_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_custom_layout_new$MH = RuntimeHelper.downcallHandle(
        "gtk_custom_layout_new",
        constants$2027.gtk_custom_layout_new$FUNC
    );
    static final FunctionDescriptor gtk_custom_sorter_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_custom_sorter_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_custom_sorter_get_type",
        constants$2027.gtk_custom_sorter_get_type$FUNC
    );
}


