// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1301 {

    static final FunctionDescriptor gdk_pixbuf_get_pixels$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_pixbuf_get_pixels$MH = RuntimeHelper.downcallHandle(
        "gdk_pixbuf_get_pixels",
        constants$1301.gdk_pixbuf_get_pixels$FUNC
    );
    static final FunctionDescriptor gdk_pixbuf_get_width$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_pixbuf_get_width$MH = RuntimeHelper.downcallHandle(
        "gdk_pixbuf_get_width",
        constants$1301.gdk_pixbuf_get_width$FUNC
    );
    static final FunctionDescriptor gdk_pixbuf_get_height$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_pixbuf_get_height$MH = RuntimeHelper.downcallHandle(
        "gdk_pixbuf_get_height",
        constants$1301.gdk_pixbuf_get_height$FUNC
    );
    static final FunctionDescriptor gdk_pixbuf_get_rowstride$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_pixbuf_get_rowstride$MH = RuntimeHelper.downcallHandle(
        "gdk_pixbuf_get_rowstride",
        constants$1301.gdk_pixbuf_get_rowstride$FUNC
    );
    static final FunctionDescriptor gdk_pixbuf_get_byte_length$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_pixbuf_get_byte_length$MH = RuntimeHelper.downcallHandle(
        "gdk_pixbuf_get_byte_length",
        constants$1301.gdk_pixbuf_get_byte_length$FUNC
    );
    static final FunctionDescriptor gdk_pixbuf_get_pixels_with_length$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_pixbuf_get_pixels_with_length$MH = RuntimeHelper.downcallHandle(
        "gdk_pixbuf_get_pixels_with_length",
        constants$1301.gdk_pixbuf_get_pixels_with_length$FUNC
    );
}


