// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1195 {

    static final FunctionDescriptor hb_buffer_message_func_t$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle hb_buffer_message_func_t$MH = RuntimeHelper.downcallHandle(
        constants$1195.hb_buffer_message_func_t$FUNC
    );
    static final FunctionDescriptor hb_buffer_set_message_func$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle hb_buffer_set_message_func$MH = RuntimeHelper.downcallHandle(
        "hb_buffer_set_message_func",
        constants$1195.hb_buffer_set_message_func$FUNC
    );
    static final FunctionDescriptor hb_font_get_glyph_func_t$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle hb_font_get_glyph_func_t$MH = RuntimeHelper.downcallHandle(
        constants$1195.hb_font_get_glyph_func_t$FUNC
    );
    static final FunctionDescriptor hb_font_funcs_set_glyph_func$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle hb_font_funcs_set_glyph_func$MH = RuntimeHelper.downcallHandle(
        "hb_font_funcs_set_glyph_func",
        constants$1195.hb_font_funcs_set_glyph_func$FUNC
    );
}


