// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1515 {

    static final FunctionDescriptor __isinf$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __isinf$MH = RuntimeHelper.downcallHandle(
        "__isinf",
        constants$1515.__isinf$FUNC
    );
    static final FunctionDescriptor __finite$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __finite$MH = RuntimeHelper.downcallHandle(
        "__finite",
        constants$1515.__finite$FUNC
    );
    static final FunctionDescriptor __isnan$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __isnan$MH = RuntimeHelper.downcallHandle(
        "__isnan",
        constants$1515.__isnan$FUNC
    );
    static final FunctionDescriptor __iseqsig$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __iseqsig$MH = RuntimeHelper.downcallHandle(
        "__iseqsig",
        constants$1515.__iseqsig$FUNC
    );
    static final FunctionDescriptor __issignaling$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __issignaling$MH = RuntimeHelper.downcallHandle(
        "__issignaling",
        constants$1515.__issignaling$FUNC
    );
    static final FunctionDescriptor acos$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle acos$MH = RuntimeHelper.downcallHandle(
        "acos",
        constants$1515.acos$FUNC
    );
}


