// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2623 {

    static final FunctionDescriptor glib_queueautoptr_cleanup_GtkTreeRowReference$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GtkTreeRowReference$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GtkTreeRowReference",
        constants$2623.glib_queueautoptr_cleanup_GtkTreeRowReference$FUNC
    );
    static final FunctionDescriptor gtk_page_setup_unix_dialog_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_page_setup_unix_dialog_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_page_setup_unix_dialog_get_type",
        constants$2623.gtk_page_setup_unix_dialog_get_type$FUNC
    );
    static final FunctionDescriptor gtk_page_setup_unix_dialog_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_page_setup_unix_dialog_new$MH = RuntimeHelper.downcallHandle(
        "gtk_page_setup_unix_dialog_new",
        constants$2623.gtk_page_setup_unix_dialog_new$FUNC
    );
    static final FunctionDescriptor gtk_page_setup_unix_dialog_set_page_setup$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_page_setup_unix_dialog_set_page_setup$MH = RuntimeHelper.downcallHandle(
        "gtk_page_setup_unix_dialog_set_page_setup",
        constants$2623.gtk_page_setup_unix_dialog_set_page_setup$FUNC
    );
    static final FunctionDescriptor gtk_page_setup_unix_dialog_get_page_setup$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_page_setup_unix_dialog_get_page_setup$MH = RuntimeHelper.downcallHandle(
        "gtk_page_setup_unix_dialog_get_page_setup",
        constants$2623.gtk_page_setup_unix_dialog_get_page_setup$FUNC
    );
    static final FunctionDescriptor gtk_page_setup_unix_dialog_set_print_settings$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_page_setup_unix_dialog_set_print_settings$MH = RuntimeHelper.downcallHandle(
        "gtk_page_setup_unix_dialog_set_print_settings",
        constants$2623.gtk_page_setup_unix_dialog_set_print_settings$FUNC
    );
}


