// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1631 {

    static final FunctionDescriptor graphene_sphere_is_empty$FUNC = FunctionDescriptor.of(Constants$root.C_BOOL$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_sphere_is_empty$MH = RuntimeHelper.downcallHandle(
        "graphene_sphere_is_empty",
        constants$1631.graphene_sphere_is_empty$FUNC
    );
    static final FunctionDescriptor graphene_sphere_equal$FUNC = FunctionDescriptor.of(Constants$root.C_BOOL$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_sphere_equal$MH = RuntimeHelper.downcallHandle(
        "graphene_sphere_equal",
        constants$1631.graphene_sphere_equal$FUNC
    );
    static final FunctionDescriptor graphene_sphere_contains_point$FUNC = FunctionDescriptor.of(Constants$root.C_BOOL$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_sphere_contains_point$MH = RuntimeHelper.downcallHandle(
        "graphene_sphere_contains_point",
        constants$1631.graphene_sphere_contains_point$FUNC
    );
    static final FunctionDescriptor graphene_sphere_distance$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_sphere_distance$MH = RuntimeHelper.downcallHandle(
        "graphene_sphere_distance",
        constants$1631.graphene_sphere_distance$FUNC
    );
    static final FunctionDescriptor graphene_sphere_get_bounding_box$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_sphere_get_bounding_box$MH = RuntimeHelper.downcallHandle(
        "graphene_sphere_get_bounding_box",
        constants$1631.graphene_sphere_get_bounding_box$FUNC
    );
    static final FunctionDescriptor graphene_sphere_translate$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_sphere_translate$MH = RuntimeHelper.downcallHandle(
        "graphene_sphere_translate",
        constants$1631.graphene_sphere_translate$FUNC
    );
}


