// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2597 {

    static final FunctionDescriptor glib_slistautoptr_cleanup_GtkStack$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GtkStack$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GtkStack",
        constants$2597.glib_slistautoptr_cleanup_GtkStack$FUNC
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GtkStack$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GtkStack$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GtkStack",
        constants$2597.glib_queueautoptr_cleanup_GtkStack$FUNC
    );
    static final FunctionDescriptor glib_autoptr_clear_GtkStackSwitcher$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GtkStackSwitcher$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GtkStackSwitcher",
        constants$2597.glib_autoptr_clear_GtkStackSwitcher$FUNC
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GtkStackSwitcher$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GtkStackSwitcher$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GtkStackSwitcher",
        constants$2597.glib_autoptr_cleanup_GtkStackSwitcher$FUNC
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GtkStackSwitcher$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GtkStackSwitcher$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GtkStackSwitcher",
        constants$2597.glib_listautoptr_cleanup_GtkStackSwitcher$FUNC
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GtkStackSwitcher$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GtkStackSwitcher$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GtkStackSwitcher",
        constants$2597.glib_slistautoptr_cleanup_GtkStackSwitcher$FUNC
    );
}


