// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1045 {

    static final FunctionDescriptor g_unix_connection_receive_credentials$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_unix_connection_receive_credentials$MH = RuntimeHelper.downcallHandle(
        "g_unix_connection_receive_credentials",
        constants$1045.g_unix_connection_receive_credentials$FUNC
    );
    static final FunctionDescriptor g_unix_connection_receive_credentials_async$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_unix_connection_receive_credentials_async$MH = RuntimeHelper.downcallHandle(
        "g_unix_connection_receive_credentials_async",
        constants$1045.g_unix_connection_receive_credentials_async$FUNC
    );
    static final FunctionDescriptor g_unix_connection_receive_credentials_finish$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_unix_connection_receive_credentials_finish$MH = RuntimeHelper.downcallHandle(
        "g_unix_connection_receive_credentials_finish",
        constants$1045.g_unix_connection_receive_credentials_finish$FUNC
    );
    static final FunctionDescriptor glib_autoptr_clear_GUnixCredentialsMessage$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GUnixCredentialsMessage$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GUnixCredentialsMessage",
        constants$1045.glib_autoptr_clear_GUnixCredentialsMessage$FUNC
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GUnixCredentialsMessage$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GUnixCredentialsMessage$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GUnixCredentialsMessage",
        constants$1045.glib_autoptr_cleanup_GUnixCredentialsMessage$FUNC
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GUnixCredentialsMessage$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GUnixCredentialsMessage$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GUnixCredentialsMessage",
        constants$1045.glib_listautoptr_cleanup_GUnixCredentialsMessage$FUNC
    );
}


