// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2765 {

    static final FunctionDescriptor ADW_HEADER_BAR$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ADW_HEADER_BAR$MH = RuntimeHelper.downcallHandle(
        "ADW_HEADER_BAR",
        constants$2765.ADW_HEADER_BAR$FUNC
    );
    static final FunctionDescriptor ADW_IS_HEADER_BAR$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ADW_IS_HEADER_BAR$MH = RuntimeHelper.downcallHandle(
        "ADW_IS_HEADER_BAR",
        constants$2765.ADW_IS_HEADER_BAR$FUNC
    );
    static final FunctionDescriptor adw_header_bar_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle adw_header_bar_new$MH = RuntimeHelper.downcallHandle(
        "adw_header_bar_new",
        constants$2765.adw_header_bar_new$FUNC
    );
    static final FunctionDescriptor adw_header_bar_get_title_widget$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle adw_header_bar_get_title_widget$MH = RuntimeHelper.downcallHandle(
        "adw_header_bar_get_title_widget",
        constants$2765.adw_header_bar_get_title_widget$FUNC
    );
    static final FunctionDescriptor adw_header_bar_set_title_widget$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle adw_header_bar_set_title_widget$MH = RuntimeHelper.downcallHandle(
        "adw_header_bar_set_title_widget",
        constants$2765.adw_header_bar_set_title_widget$FUNC
    );
    static final FunctionDescriptor adw_header_bar_pack_start$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle adw_header_bar_pack_start$MH = RuntimeHelper.downcallHandle(
        "adw_header_bar_pack_start",
        constants$2765.adw_header_bar_pack_start$FUNC
    );
}


