// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1163 {

    static final FunctionDescriptor hb_draw_cubic_to$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle hb_draw_cubic_to$MH = RuntimeHelper.downcallHandle(
        "hb_draw_cubic_to",
        constants$1163.hb_draw_cubic_to$FUNC
    );
    static final FunctionDescriptor hb_draw_close_path$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle hb_draw_close_path$MH = RuntimeHelper.downcallHandle(
        "hb_draw_close_path",
        constants$1163.hb_draw_close_path$FUNC
    );
    static final FunctionDescriptor hb_font_funcs_create$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle hb_font_funcs_create$MH = RuntimeHelper.downcallHandle(
        "hb_font_funcs_create",
        constants$1163.hb_font_funcs_create$FUNC
    );
    static final FunctionDescriptor hb_font_funcs_get_empty$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle hb_font_funcs_get_empty$MH = RuntimeHelper.downcallHandle(
        "hb_font_funcs_get_empty",
        constants$1163.hb_font_funcs_get_empty$FUNC
    );
    static final FunctionDescriptor hb_font_funcs_reference$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle hb_font_funcs_reference$MH = RuntimeHelper.downcallHandle(
        "hb_font_funcs_reference",
        constants$1163.hb_font_funcs_reference$FUNC
    );
    static final FunctionDescriptor hb_font_funcs_destroy$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle hb_font_funcs_destroy$MH = RuntimeHelper.downcallHandle(
        "hb_font_funcs_destroy",
        constants$1163.hb_font_funcs_destroy$FUNC
    );
}


