// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1261 {

    static final FunctionDescriptor pango_variant_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle pango_variant_get_type$MH = RuntimeHelper.downcallHandle(
        "pango_variant_get_type",
        constants$1261.pango_variant_get_type$FUNC
    );
    static final FunctionDescriptor pango_weight_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle pango_weight_get_type$MH = RuntimeHelper.downcallHandle(
        "pango_weight_get_type",
        constants$1261.pango_weight_get_type$FUNC
    );
    static final FunctionDescriptor pango_stretch_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle pango_stretch_get_type$MH = RuntimeHelper.downcallHandle(
        "pango_stretch_get_type",
        constants$1261.pango_stretch_get_type$FUNC
    );
    static final FunctionDescriptor pango_font_mask_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle pango_font_mask_get_type$MH = RuntimeHelper.downcallHandle(
        "pango_font_mask_get_type",
        constants$1261.pango_font_mask_get_type$FUNC
    );
    static final FunctionDescriptor pango_shape_flags_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle pango_shape_flags_get_type$MH = RuntimeHelper.downcallHandle(
        "pango_shape_flags_get_type",
        constants$1261.pango_shape_flags_get_type$FUNC
    );
    static final FunctionDescriptor pango_gravity_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle pango_gravity_get_type$MH = RuntimeHelper.downcallHandle(
        "pango_gravity_get_type",
        constants$1261.pango_gravity_get_type$FUNC
    );
}


