// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2203 {

    static final FunctionDescriptor GTK_MEDIA_FILE_CLASS$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GTK_MEDIA_FILE_CLASS$MH = RuntimeHelper.downcallHandle(
        "GTK_MEDIA_FILE_CLASS",
        constants$2203.GTK_MEDIA_FILE_CLASS$FUNC
    );
    static final FunctionDescriptor GTK_IS_MEDIA_FILE$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GTK_IS_MEDIA_FILE$MH = RuntimeHelper.downcallHandle(
        "GTK_IS_MEDIA_FILE",
        constants$2203.GTK_IS_MEDIA_FILE$FUNC
    );
    static final FunctionDescriptor GTK_IS_MEDIA_FILE_CLASS$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GTK_IS_MEDIA_FILE_CLASS$MH = RuntimeHelper.downcallHandle(
        "GTK_IS_MEDIA_FILE_CLASS",
        constants$2203.GTK_IS_MEDIA_FILE_CLASS$FUNC
    );
    static final FunctionDescriptor GTK_MEDIA_FILE_GET_CLASS$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GTK_MEDIA_FILE_GET_CLASS$MH = RuntimeHelper.downcallHandle(
        "GTK_MEDIA_FILE_GET_CLASS",
        constants$2203.GTK_MEDIA_FILE_GET_CLASS$FUNC
    );
    static final FunctionDescriptor gtk_media_file_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle gtk_media_file_new$MH = RuntimeHelper.downcallHandle(
        "gtk_media_file_new",
        constants$2203.gtk_media_file_new$FUNC
    );
    static final FunctionDescriptor gtk_media_file_new_for_filename$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_media_file_new_for_filename$MH = RuntimeHelper.downcallHandle(
        "gtk_media_file_new_for_filename",
        constants$2203.gtk_media_file_new_for_filename$FUNC
    );
}


