// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1432 {

    static final FunctionDescriptor glib_queueautoptr_cleanup_GdkContentProvider$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GdkContentProvider$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GdkContentProvider",
        constants$1432.glib_queueautoptr_cleanup_GdkContentProvider$FUNC
    );
    static final FunctionDescriptor glib_autoptr_clear_GdkCursor$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GdkCursor$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GdkCursor",
        constants$1432.glib_autoptr_clear_GdkCursor$FUNC
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GdkCursor$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GdkCursor$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GdkCursor",
        constants$1432.glib_autoptr_cleanup_GdkCursor$FUNC
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GdkCursor$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GdkCursor$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GdkCursor",
        constants$1432.glib_listautoptr_cleanup_GdkCursor$FUNC
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GdkCursor$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GdkCursor$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GdkCursor",
        constants$1432.glib_slistautoptr_cleanup_GdkCursor$FUNC
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GdkCursor$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GdkCursor$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GdkCursor",
        constants$1432.glib_queueautoptr_cleanup_GdkCursor$FUNC
    );
}


