// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2790 {

    static final FunctionDescriptor adw_toast_get_button_label$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle adw_toast_get_button_label$MH = RuntimeHelper.downcallHandle(
        "adw_toast_get_button_label",
        constants$2790.adw_toast_get_button_label$FUNC
    );
    static final FunctionDescriptor adw_toast_set_button_label$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle adw_toast_set_button_label$MH = RuntimeHelper.downcallHandle(
        "adw_toast_set_button_label",
        constants$2790.adw_toast_set_button_label$FUNC
    );
    static final FunctionDescriptor adw_toast_get_action_name$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle adw_toast_get_action_name$MH = RuntimeHelper.downcallHandle(
        "adw_toast_get_action_name",
        constants$2790.adw_toast_get_action_name$FUNC
    );
    static final FunctionDescriptor adw_toast_set_action_name$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle adw_toast_set_action_name$MH = RuntimeHelper.downcallHandle(
        "adw_toast_set_action_name",
        constants$2790.adw_toast_set_action_name$FUNC
    );
    static final FunctionDescriptor adw_toast_get_action_target_value$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle adw_toast_get_action_target_value$MH = RuntimeHelper.downcallHandle(
        "adw_toast_get_action_target_value",
        constants$2790.adw_toast_get_action_target_value$FUNC
    );
    static final FunctionDescriptor adw_toast_set_action_target_value$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle adw_toast_set_action_target_value$MH = RuntimeHelper.downcallHandle(
        "adw_toast_set_action_target_value",
        constants$2790.adw_toast_set_action_target_value$FUNC
    );
}


