// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1202 {

    static final FunctionDescriptor hb_shape_plan_set_user_data$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle hb_shape_plan_set_user_data$MH = RuntimeHelper.downcallHandle(
        "hb_shape_plan_set_user_data",
        constants$1202.hb_shape_plan_set_user_data$FUNC
    );
    static final FunctionDescriptor hb_shape_plan_get_user_data$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle hb_shape_plan_get_user_data$MH = RuntimeHelper.downcallHandle(
        "hb_shape_plan_get_user_data",
        constants$1202.hb_shape_plan_get_user_data$FUNC
    );
    static final FunctionDescriptor hb_shape_plan_execute$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle hb_shape_plan_execute$MH = RuntimeHelper.downcallHandle(
        "hb_shape_plan_execute",
        constants$1202.hb_shape_plan_execute$FUNC
    );
    static final FunctionDescriptor hb_shape_plan_get_shaper$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle hb_shape_plan_get_shaper$MH = RuntimeHelper.downcallHandle(
        "hb_shape_plan_get_shaper",
        constants$1202.hb_shape_plan_get_shaper$FUNC
    );
    static final FunctionDescriptor hb_style_get_value$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle hb_style_get_value$MH = RuntimeHelper.downcallHandle(
        "hb_style_get_value",
        constants$1202.hb_style_get_value$FUNC
    );
    static final FunctionDescriptor hb_version$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle hb_version$MH = RuntimeHelper.downcallHandle(
        "hb_version",
        constants$1202.hb_version$FUNC
    );
}


