// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1787 {

    static final FunctionDescriptor glib_autoptr_cleanup_GtkShortcutsWindow$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GtkShortcutsWindow$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GtkShortcutsWindow",
        constants$1787.glib_autoptr_cleanup_GtkShortcutsWindow$FUNC
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GtkShortcutsWindow$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GtkShortcutsWindow$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GtkShortcutsWindow",
        constants$1787.glib_listautoptr_cleanup_GtkShortcutsWindow$FUNC
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GtkShortcutsWindow$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GtkShortcutsWindow$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GtkShortcutsWindow",
        constants$1787.glib_slistautoptr_cleanup_GtkShortcutsWindow$FUNC
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GtkShortcutsWindow$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GtkShortcutsWindow$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GtkShortcutsWindow",
        constants$1787.glib_queueautoptr_cleanup_GtkShortcutsWindow$FUNC
    );
    static final FunctionDescriptor gtk_application_window_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_application_window_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_application_window_get_type",
        constants$1787.gtk_application_window_get_type$FUNC
    );
    static final FunctionDescriptor gtk_application_window_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_application_window_new$MH = RuntimeHelper.downcallHandle(
        "gtk_application_window_new",
        constants$1787.gtk_application_window_new$FUNC
    );
}


