// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2376 {

    static final FunctionDescriptor gtk_stack_page_set_icon_name$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_stack_page_set_icon_name$MH = RuntimeHelper.downcallHandle(
        "gtk_stack_page_set_icon_name",
        constants$2376.gtk_stack_page_set_icon_name$FUNC
    );
    static final FunctionDescriptor gtk_stack_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_stack_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_stack_get_type",
        constants$2376.gtk_stack_get_type$FUNC
    );
    static final FunctionDescriptor gtk_stack_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle gtk_stack_new$MH = RuntimeHelper.downcallHandle(
        "gtk_stack_new",
        constants$2376.gtk_stack_new$FUNC
    );
    static final FunctionDescriptor gtk_stack_add_child$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_stack_add_child$MH = RuntimeHelper.downcallHandle(
        "gtk_stack_add_child",
        constants$2376.gtk_stack_add_child$FUNC
    );
    static final FunctionDescriptor gtk_stack_add_named$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_stack_add_named$MH = RuntimeHelper.downcallHandle(
        "gtk_stack_add_named",
        constants$2376.gtk_stack_add_named$FUNC
    );
    static final FunctionDescriptor gtk_stack_add_titled$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_stack_add_titled$MH = RuntimeHelper.downcallHandle(
        "gtk_stack_add_titled",
        constants$2376.gtk_stack_add_titled$FUNC
    );
}


