// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2655 {

    static final FunctionDescriptor hb_ot_var_get_named_instance_count$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle hb_ot_var_get_named_instance_count$MH = RuntimeHelper.downcallHandle(
        "hb_ot_var_get_named_instance_count",
        constants$2655.hb_ot_var_get_named_instance_count$FUNC
    );
    static final FunctionDescriptor hb_ot_var_named_instance_get_subfamily_name_id$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle hb_ot_var_named_instance_get_subfamily_name_id$MH = RuntimeHelper.downcallHandle(
        "hb_ot_var_named_instance_get_subfamily_name_id",
        constants$2655.hb_ot_var_named_instance_get_subfamily_name_id$FUNC
    );
    static final FunctionDescriptor hb_ot_var_named_instance_get_postscript_name_id$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle hb_ot_var_named_instance_get_postscript_name_id$MH = RuntimeHelper.downcallHandle(
        "hb_ot_var_named_instance_get_postscript_name_id",
        constants$2655.hb_ot_var_named_instance_get_postscript_name_id$FUNC
    );
    static final FunctionDescriptor hb_ot_var_named_instance_get_design_coords$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle hb_ot_var_named_instance_get_design_coords$MH = RuntimeHelper.downcallHandle(
        "hb_ot_var_named_instance_get_design_coords",
        constants$2655.hb_ot_var_named_instance_get_design_coords$FUNC
    );
    static final FunctionDescriptor hb_ot_var_normalize_variations$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle hb_ot_var_normalize_variations$MH = RuntimeHelper.downcallHandle(
        "hb_ot_var_normalize_variations",
        constants$2655.hb_ot_var_normalize_variations$FUNC
    );
    static final FunctionDescriptor hb_ot_var_normalize_coords$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle hb_ot_var_normalize_coords$MH = RuntimeHelper.downcallHandle(
        "hb_ot_var_normalize_coords",
        constants$2655.hb_ot_var_normalize_coords$FUNC
    );
}


