// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2473 {

    static final FunctionDescriptor gtk_tree_expander_set_list_row$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_tree_expander_set_list_row$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_expander_set_list_row",
        constants$2473.gtk_tree_expander_set_list_row$FUNC
    );
    static final FunctionDescriptor gtk_tree_expander_get_indent_for_icon$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_tree_expander_get_indent_for_icon$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_expander_get_indent_for_icon",
        constants$2473.gtk_tree_expander_get_indent_for_icon$FUNC
    );
    static final FunctionDescriptor gtk_tree_expander_set_indent_for_icon$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_tree_expander_set_indent_for_icon$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_expander_set_indent_for_icon",
        constants$2473.gtk_tree_expander_set_indent_for_icon$FUNC
    );
    static final FunctionDescriptor gtk_tree_list_row_sorter_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_tree_list_row_sorter_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_list_row_sorter_get_type",
        constants$2473.gtk_tree_list_row_sorter_get_type$FUNC
    );
    static final FunctionDescriptor glib_autoptr_clear_GtkTreeListRowSorter$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GtkTreeListRowSorter$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GtkTreeListRowSorter",
        constants$2473.glib_autoptr_clear_GtkTreeListRowSorter$FUNC
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GtkTreeListRowSorter$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GtkTreeListRowSorter$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GtkTreeListRowSorter",
        constants$2473.glib_autoptr_cleanup_GtkTreeListRowSorter$FUNC
    );
}


