// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1280 {

    static final FunctionDescriptor pango_layout_get_line_count$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_layout_get_line_count$MH = RuntimeHelper.downcallHandle(
        "pango_layout_get_line_count",
        constants$1280.pango_layout_get_line_count$FUNC
    );
    static final FunctionDescriptor pango_layout_get_line$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle pango_layout_get_line$MH = RuntimeHelper.downcallHandle(
        "pango_layout_get_line",
        constants$1280.pango_layout_get_line$FUNC
    );
    static final FunctionDescriptor pango_layout_get_line_readonly$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle pango_layout_get_line_readonly$MH = RuntimeHelper.downcallHandle(
        "pango_layout_get_line_readonly",
        constants$1280.pango_layout_get_line_readonly$FUNC
    );
    static final FunctionDescriptor pango_layout_get_lines$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_layout_get_lines$MH = RuntimeHelper.downcallHandle(
        "pango_layout_get_lines",
        constants$1280.pango_layout_get_lines$FUNC
    );
    static final FunctionDescriptor pango_layout_get_lines_readonly$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_layout_get_lines_readonly$MH = RuntimeHelper.downcallHandle(
        "pango_layout_get_lines_readonly",
        constants$1280.pango_layout_get_lines_readonly$FUNC
    );
    static final FunctionDescriptor pango_layout_serialize$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle pango_layout_serialize$MH = RuntimeHelper.downcallHandle(
        "pango_layout_serialize",
        constants$1280.pango_layout_serialize$FUNC
    );
}


