// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2182 {

    static final FunctionDescriptor gtk_list_item_get_child$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_list_item_get_child$MH = RuntimeHelper.downcallHandle(
        "gtk_list_item_get_child",
        constants$2182.gtk_list_item_get_child$FUNC
    );
    static final FunctionDescriptor gtk_list_view_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_list_view_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_list_view_get_type",
        constants$2182.gtk_list_view_get_type$FUNC
    );
    static final FunctionDescriptor gtk_list_view_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_list_view_new$MH = RuntimeHelper.downcallHandle(
        "gtk_list_view_new",
        constants$2182.gtk_list_view_new$FUNC
    );
    static final FunctionDescriptor gtk_list_view_get_model$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_list_view_get_model$MH = RuntimeHelper.downcallHandle(
        "gtk_list_view_get_model",
        constants$2182.gtk_list_view_get_model$FUNC
    );
    static final FunctionDescriptor gtk_list_view_set_model$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_list_view_set_model$MH = RuntimeHelper.downcallHandle(
        "gtk_list_view_set_model",
        constants$2182.gtk_list_view_set_model$FUNC
    );
    static final FunctionDescriptor gtk_list_view_set_factory$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_list_view_set_factory$MH = RuntimeHelper.downcallHandle(
        "gtk_list_view_set_factory",
        constants$2182.gtk_list_view_set_factory$FUNC
    );
}


