// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2635 {

    static final FunctionDescriptor gtk_print_unix_dialog_get_page_setup$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_print_unix_dialog_get_page_setup$MH = RuntimeHelper.downcallHandle(
        "gtk_print_unix_dialog_get_page_setup",
        constants$2635.gtk_print_unix_dialog_get_page_setup$FUNC
    );
    static final FunctionDescriptor gtk_print_unix_dialog_set_current_page$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_print_unix_dialog_set_current_page$MH = RuntimeHelper.downcallHandle(
        "gtk_print_unix_dialog_set_current_page",
        constants$2635.gtk_print_unix_dialog_set_current_page$FUNC
    );
    static final FunctionDescriptor gtk_print_unix_dialog_get_current_page$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_print_unix_dialog_get_current_page$MH = RuntimeHelper.downcallHandle(
        "gtk_print_unix_dialog_get_current_page",
        constants$2635.gtk_print_unix_dialog_get_current_page$FUNC
    );
    static final FunctionDescriptor gtk_print_unix_dialog_set_settings$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_print_unix_dialog_set_settings$MH = RuntimeHelper.downcallHandle(
        "gtk_print_unix_dialog_set_settings",
        constants$2635.gtk_print_unix_dialog_set_settings$FUNC
    );
    static final FunctionDescriptor gtk_print_unix_dialog_get_settings$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_print_unix_dialog_get_settings$MH = RuntimeHelper.downcallHandle(
        "gtk_print_unix_dialog_get_settings",
        constants$2635.gtk_print_unix_dialog_get_settings$FUNC
    );
    static final FunctionDescriptor gtk_print_unix_dialog_get_selected_printer$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_print_unix_dialog_get_selected_printer$MH = RuntimeHelper.downcallHandle(
        "gtk_print_unix_dialog_get_selected_printer",
        constants$2635.gtk_print_unix_dialog_get_selected_printer$FUNC
    );
}


