// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1577 {

    static final FunctionDescriptor graphene_simd4x4f_scale$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle graphene_simd4x4f_scale$MH = RuntimeHelper.downcallHandle(
        "graphene_simd4x4f_scale",
        constants$1577.graphene_simd4x4f_scale$FUNC
    );
    static final FunctionDescriptor graphene_simd4x4f_rotation$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_simd4x4f_rotation$MH = RuntimeHelper.downcallHandle(
        "graphene_simd4x4f_rotation",
        constants$1577.graphene_simd4x4f_rotation$FUNC
    );
    static final FunctionDescriptor graphene_simd4x4f_add$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_simd4x4f_add$MH = RuntimeHelper.downcallHandle(
        "graphene_simd4x4f_add",
        constants$1577.graphene_simd4x4f_add$FUNC
    );
    static final FunctionDescriptor graphene_simd4x4f_sub$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_simd4x4f_sub$MH = RuntimeHelper.downcallHandle(
        "graphene_simd4x4f_sub",
        constants$1577.graphene_simd4x4f_sub$FUNC
    );
    static final FunctionDescriptor graphene_simd4x4f_mul$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_simd4x4f_mul$MH = RuntimeHelper.downcallHandle(
        "graphene_simd4x4f_mul",
        constants$1577.graphene_simd4x4f_mul$FUNC
    );
    static final FunctionDescriptor graphene_simd4x4f_div$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_simd4x4f_div$MH = RuntimeHelper.downcallHandle(
        "graphene_simd4x4f_div",
        constants$1577.graphene_simd4x4f_div$FUNC
    );
}


