// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2593 {

    static final FunctionDescriptor glib_queueautoptr_cleanup_GtkSettings$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GtkSettings$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GtkSettings",
        constants$2593.glib_queueautoptr_cleanup_GtkSettings$FUNC
    );
    static final FunctionDescriptor glib_autoptr_clear_GtkStackSidebar$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GtkStackSidebar$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GtkStackSidebar",
        constants$2593.glib_autoptr_clear_GtkStackSidebar$FUNC
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GtkStackSidebar$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GtkStackSidebar$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GtkStackSidebar",
        constants$2593.glib_autoptr_cleanup_GtkStackSidebar$FUNC
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GtkStackSidebar$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GtkStackSidebar$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GtkStackSidebar",
        constants$2593.glib_listautoptr_cleanup_GtkStackSidebar$FUNC
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GtkStackSidebar$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GtkStackSidebar$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GtkStackSidebar",
        constants$2593.glib_slistautoptr_cleanup_GtkStackSidebar$FUNC
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GtkStackSidebar$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GtkStackSidebar$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GtkStackSidebar",
        constants$2593.glib_queueautoptr_cleanup_GtkStackSidebar$FUNC
    );
}


