// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2692 {

    static final FunctionDescriptor glib_autoptr_clear_AdwAnimation$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_AdwAnimation$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_AdwAnimation",
        constants$2692.glib_autoptr_clear_AdwAnimation$FUNC
    );
    static final FunctionDescriptor glib_autoptr_cleanup_AdwAnimation$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_AdwAnimation$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_AdwAnimation",
        constants$2692.glib_autoptr_cleanup_AdwAnimation$FUNC
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_AdwAnimation$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_AdwAnimation$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_AdwAnimation",
        constants$2692.glib_listautoptr_cleanup_AdwAnimation$FUNC
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_AdwAnimation$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_AdwAnimation$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_AdwAnimation",
        constants$2692.glib_slistautoptr_cleanup_AdwAnimation$FUNC
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_AdwAnimation$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_AdwAnimation$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_AdwAnimation",
        constants$2692.glib_queueautoptr_cleanup_AdwAnimation$FUNC
    );
    static final FunctionDescriptor glib_autoptr_clear_AdwAnimationClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_AdwAnimationClass$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_AdwAnimationClass",
        constants$2692.glib_autoptr_clear_AdwAnimationClass$FUNC
    );
}


