// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2146 {

    static final FunctionDescriptor gtk_icon_view_get_item_padding$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_icon_view_get_item_padding$MH = RuntimeHelper.downcallHandle(
        "gtk_icon_view_get_item_padding",
        constants$2146.gtk_icon_view_get_item_padding$FUNC
    );
    static final FunctionDescriptor gtk_icon_view_get_path_at_pos$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_icon_view_get_path_at_pos$MH = RuntimeHelper.downcallHandle(
        "gtk_icon_view_get_path_at_pos",
        constants$2146.gtk_icon_view_get_path_at_pos$FUNC
    );
    static final FunctionDescriptor gtk_icon_view_get_item_at_pos$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_icon_view_get_item_at_pos$MH = RuntimeHelper.downcallHandle(
        "gtk_icon_view_get_item_at_pos",
        constants$2146.gtk_icon_view_get_item_at_pos$FUNC
    );
    static final FunctionDescriptor gtk_icon_view_get_visible_range$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_icon_view_get_visible_range$MH = RuntimeHelper.downcallHandle(
        "gtk_icon_view_get_visible_range",
        constants$2146.gtk_icon_view_get_visible_range$FUNC
    );
    static final FunctionDescriptor gtk_icon_view_set_activate_on_single_click$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_icon_view_set_activate_on_single_click$MH = RuntimeHelper.downcallHandle(
        "gtk_icon_view_set_activate_on_single_click",
        constants$2146.gtk_icon_view_set_activate_on_single_click$FUNC
    );
    static final FunctionDescriptor gtk_icon_view_get_activate_on_single_click$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_icon_view_get_activate_on_single_click$MH = RuntimeHelper.downcallHandle(
        "gtk_icon_view_get_activate_on_single_click",
        constants$2146.gtk_icon_view_get_activate_on_single_click$FUNC
    );
}


