// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1344 {

    static final FunctionDescriptor gdk_content_deserializer_get_priority$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_content_deserializer_get_priority$MH = RuntimeHelper.downcallHandle(
        "gdk_content_deserializer_get_priority",
        constants$1344.gdk_content_deserializer_get_priority$FUNC
    );
    static final FunctionDescriptor gdk_content_deserializer_get_cancellable$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_content_deserializer_get_cancellable$MH = RuntimeHelper.downcallHandle(
        "gdk_content_deserializer_get_cancellable",
        constants$1344.gdk_content_deserializer_get_cancellable$FUNC
    );
    static final FunctionDescriptor gdk_content_deserializer_get_user_data$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_content_deserializer_get_user_data$MH = RuntimeHelper.downcallHandle(
        "gdk_content_deserializer_get_user_data",
        constants$1344.gdk_content_deserializer_get_user_data$FUNC
    );
    static final FunctionDescriptor gdk_content_deserializer_set_task_data$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_content_deserializer_set_task_data$MH = RuntimeHelper.downcallHandle(
        "gdk_content_deserializer_set_task_data",
        constants$1344.gdk_content_deserializer_set_task_data$FUNC
    );
    static final FunctionDescriptor gdk_content_deserializer_get_task_data$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_content_deserializer_get_task_data$MH = RuntimeHelper.downcallHandle(
        "gdk_content_deserializer_get_task_data",
        constants$1344.gdk_content_deserializer_get_task_data$FUNC
    );
    static final FunctionDescriptor gdk_content_deserializer_return_success$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_content_deserializer_return_success$MH = RuntimeHelper.downcallHandle(
        "gdk_content_deserializer_return_success",
        constants$1344.gdk_content_deserializer_return_success$FUNC
    );
}


