// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1982 {

    static final FunctionDescriptor gtk_tree_view_get_tooltip_column$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_tree_view_get_tooltip_column$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_view_get_tooltip_column",
        constants$1982.gtk_tree_view_get_tooltip_column$FUNC
    );
    static final FunctionDescriptor gtk_combo_box_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_combo_box_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_combo_box_get_type",
        constants$1982.gtk_combo_box_get_type$FUNC
    );
    static final FunctionDescriptor gtk_combo_box_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle gtk_combo_box_new$MH = RuntimeHelper.downcallHandle(
        "gtk_combo_box_new",
        constants$1982.gtk_combo_box_new$FUNC
    );
    static final FunctionDescriptor gtk_combo_box_new_with_entry$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle gtk_combo_box_new_with_entry$MH = RuntimeHelper.downcallHandle(
        "gtk_combo_box_new_with_entry",
        constants$1982.gtk_combo_box_new_with_entry$FUNC
    );
    static final FunctionDescriptor gtk_combo_box_new_with_model$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_combo_box_new_with_model$MH = RuntimeHelper.downcallHandle(
        "gtk_combo_box_new_with_model",
        constants$1982.gtk_combo_box_new_with_model$FUNC
    );
    static final FunctionDescriptor gtk_combo_box_new_with_model_and_entry$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_combo_box_new_with_model_and_entry$MH = RuntimeHelper.downcallHandle(
        "gtk_combo_box_new_with_model_and_entry",
        constants$1982.gtk_combo_box_new_with_model_and_entry$FUNC
    );
}


