// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2664 {

    static final FunctionDescriptor FT_Init_FreeType$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle FT_Init_FreeType$MH = RuntimeHelper.downcallHandle(
        "FT_Init_FreeType",
        constants$2664.FT_Init_FreeType$FUNC
    );
    static final FunctionDescriptor FT_Done_FreeType$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle FT_Done_FreeType$MH = RuntimeHelper.downcallHandle(
        "FT_Done_FreeType",
        constants$2664.FT_Done_FreeType$FUNC
    );
    static final FunctionDescriptor FT_New_Face$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle FT_New_Face$MH = RuntimeHelper.downcallHandle(
        "FT_New_Face",
        constants$2664.FT_New_Face$FUNC
    );
    static final FunctionDescriptor FT_New_Memory_Face$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle FT_New_Memory_Face$MH = RuntimeHelper.downcallHandle(
        "FT_New_Memory_Face",
        constants$2664.FT_New_Memory_Face$FUNC
    );
    static final FunctionDescriptor FT_Open_Face$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle FT_Open_Face$MH = RuntimeHelper.downcallHandle(
        "FT_Open_Face",
        constants$2664.FT_Open_Face$FUNC
    );
    static final FunctionDescriptor FT_Attach_File$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle FT_Attach_File$MH = RuntimeHelper.downcallHandle(
        "FT_Attach_File",
        constants$2664.FT_Attach_File$FUNC
    );
}


