// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2212 {

    static final FunctionDescriptor gtk_menu_button_set_use_underline$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_menu_button_set_use_underline$MH = RuntimeHelper.downcallHandle(
        "gtk_menu_button_set_use_underline",
        constants$2212.gtk_menu_button_set_use_underline$FUNC
    );
    static final FunctionDescriptor gtk_menu_button_get_use_underline$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_menu_button_get_use_underline$MH = RuntimeHelper.downcallHandle(
        "gtk_menu_button_get_use_underline",
        constants$2212.gtk_menu_button_get_use_underline$FUNC
    );
    static final FunctionDescriptor gtk_menu_button_set_has_frame$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_menu_button_set_has_frame$MH = RuntimeHelper.downcallHandle(
        "gtk_menu_button_set_has_frame",
        constants$2212.gtk_menu_button_set_has_frame$FUNC
    );
    static final FunctionDescriptor gtk_menu_button_get_has_frame$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_menu_button_get_has_frame$MH = RuntimeHelper.downcallHandle(
        "gtk_menu_button_get_has_frame",
        constants$2212.gtk_menu_button_get_has_frame$FUNC
    );
    static final FunctionDescriptor gtk_menu_button_popup$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_menu_button_popup$MH = RuntimeHelper.downcallHandle(
        "gtk_menu_button_popup",
        constants$2212.gtk_menu_button_popup$FUNC
    );
    static final FunctionDescriptor gtk_menu_button_popdown$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_menu_button_popdown$MH = RuntimeHelper.downcallHandle(
        "gtk_menu_button_popdown",
        constants$2212.gtk_menu_button_popdown$FUNC
    );
}


