// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2045 {

    static final FunctionDescriptor gtk_drop_target_set_preload$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_drop_target_set_preload$MH = RuntimeHelper.downcallHandle(
        "gtk_drop_target_set_preload",
        constants$2045.gtk_drop_target_set_preload$FUNC
    );
    static final FunctionDescriptor gtk_drop_target_get_preload$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_drop_target_get_preload$MH = RuntimeHelper.downcallHandle(
        "gtk_drop_target_get_preload",
        constants$2045.gtk_drop_target_get_preload$FUNC
    );
    static final FunctionDescriptor gtk_drop_target_get_drop$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_drop_target_get_drop$MH = RuntimeHelper.downcallHandle(
        "gtk_drop_target_get_drop",
        constants$2045.gtk_drop_target_get_drop$FUNC
    );
    static final FunctionDescriptor gtk_drop_target_get_current_drop$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_drop_target_get_current_drop$MH = RuntimeHelper.downcallHandle(
        "gtk_drop_target_get_current_drop",
        constants$2045.gtk_drop_target_get_current_drop$FUNC
    );
    static final FunctionDescriptor gtk_drop_target_get_value$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_drop_target_get_value$MH = RuntimeHelper.downcallHandle(
        "gtk_drop_target_get_value",
        constants$2045.gtk_drop_target_get_value$FUNC
    );
    static final FunctionDescriptor gtk_drop_target_reject$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_drop_target_reject$MH = RuntimeHelper.downcallHandle(
        "gtk_drop_target_reject",
        constants$2045.gtk_drop_target_reject$FUNC
    );
}


