// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1604 {

    static final FunctionDescriptor graphene_matrix_get_x_scale$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_matrix_get_x_scale$MH = RuntimeHelper.downcallHandle(
        "graphene_matrix_get_x_scale",
        constants$1604.graphene_matrix_get_x_scale$FUNC
    );
    static final FunctionDescriptor graphene_matrix_get_y_scale$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_matrix_get_y_scale$MH = RuntimeHelper.downcallHandle(
        "graphene_matrix_get_y_scale",
        constants$1604.graphene_matrix_get_y_scale$FUNC
    );
    static final FunctionDescriptor graphene_matrix_get_z_scale$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_matrix_get_z_scale$MH = RuntimeHelper.downcallHandle(
        "graphene_matrix_get_z_scale",
        constants$1604.graphene_matrix_get_z_scale$FUNC
    );
    static final FunctionDescriptor graphene_matrix_interpolate$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_matrix_interpolate$MH = RuntimeHelper.downcallHandle(
        "graphene_matrix_interpolate",
        constants$1604.graphene_matrix_interpolate$FUNC
    );
    static final FunctionDescriptor graphene_matrix_near$FUNC = FunctionDescriptor.of(Constants$root.C_BOOL$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle graphene_matrix_near$MH = RuntimeHelper.downcallHandle(
        "graphene_matrix_near",
        constants$1604.graphene_matrix_near$FUNC
    );
    static final FunctionDescriptor graphene_matrix_equal$FUNC = FunctionDescriptor.of(Constants$root.C_BOOL$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_matrix_equal$MH = RuntimeHelper.downcallHandle(
        "graphene_matrix_equal",
        constants$1604.graphene_matrix_equal$FUNC
    );
}


