// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1698 {

    static final FunctionDescriptor gtk_nothing_action_get$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle gtk_nothing_action_get$MH = RuntimeHelper.downcallHandle(
        "gtk_nothing_action_get",
        constants$1698.gtk_nothing_action_get$FUNC
    );
    static final FunctionDescriptor gtk_callback_action_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_callback_action_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_callback_action_get_type",
        constants$1698.gtk_callback_action_get_type$FUNC
    );
    static final FunctionDescriptor glib_autoptr_clear_GtkCallbackAction$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GtkCallbackAction$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GtkCallbackAction",
        constants$1698.glib_autoptr_clear_GtkCallbackAction$FUNC
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GtkCallbackAction$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GtkCallbackAction$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GtkCallbackAction",
        constants$1698.glib_autoptr_cleanup_GtkCallbackAction$FUNC
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GtkCallbackAction$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GtkCallbackAction$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GtkCallbackAction",
        constants$1698.glib_listautoptr_cleanup_GtkCallbackAction$FUNC
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GtkCallbackAction$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GtkCallbackAction$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GtkCallbackAction",
        constants$1698.glib_slistautoptr_cleanup_GtkCallbackAction$FUNC
    );
}


