// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2482 {

    static final FunctionDescriptor gtk_tree_store_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_tree_store_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_store_get_type",
        constants$2482.gtk_tree_store_get_type$FUNC
    );
    static final FunctionDescriptor gtk_tree_store_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_tree_store_new$MH = RuntimeHelper.downcallHandleVariadic(
        "gtk_tree_store_new",
        constants$2482.gtk_tree_store_new$FUNC
    );
    static final FunctionDescriptor gtk_tree_store_newv$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_tree_store_newv$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_store_newv",
        constants$2482.gtk_tree_store_newv$FUNC
    );
    static final FunctionDescriptor gtk_tree_store_set_column_types$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_tree_store_set_column_types$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_store_set_column_types",
        constants$2482.gtk_tree_store_set_column_types$FUNC
    );
    static final FunctionDescriptor gtk_tree_store_set_value$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_tree_store_set_value$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_store_set_value",
        constants$2482.gtk_tree_store_set_value$FUNC
    );
    static final FunctionDescriptor gtk_tree_store_set$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_tree_store_set$MH = RuntimeHelper.downcallHandleVariadic(
        "gtk_tree_store_set",
        constants$2482.gtk_tree_store_set$FUNC
    );
}


