// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1610 {

    static final FunctionDescriptor graphene_rect_get_top_left$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_rect_get_top_left$MH = RuntimeHelper.downcallHandle(
        "graphene_rect_get_top_left",
        constants$1610.graphene_rect_get_top_left$FUNC
    );
    static final FunctionDescriptor graphene_rect_get_top_right$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_rect_get_top_right$MH = RuntimeHelper.downcallHandle(
        "graphene_rect_get_top_right",
        constants$1610.graphene_rect_get_top_right$FUNC
    );
    static final FunctionDescriptor graphene_rect_get_bottom_right$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_rect_get_bottom_right$MH = RuntimeHelper.downcallHandle(
        "graphene_rect_get_bottom_right",
        constants$1610.graphene_rect_get_bottom_right$FUNC
    );
    static final FunctionDescriptor graphene_rect_get_bottom_left$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_rect_get_bottom_left$MH = RuntimeHelper.downcallHandle(
        "graphene_rect_get_bottom_left",
        constants$1610.graphene_rect_get_bottom_left$FUNC
    );
    static final FunctionDescriptor graphene_rect_get_vertices$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_rect_get_vertices$MH = RuntimeHelper.downcallHandle(
        "graphene_rect_get_vertices",
        constants$1610.graphene_rect_get_vertices$FUNC
    );
    static final FunctionDescriptor graphene_rect_get_x$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_rect_get_x$MH = RuntimeHelper.downcallHandle(
        "graphene_rect_get_x",
        constants$1610.graphene_rect_get_x$FUNC
    );
}


