// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1903 {

    static final FunctionDescriptor glib_autoptr_cleanup_GtkSorter$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GtkSorter$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GtkSorter",
        constants$1903.glib_autoptr_cleanup_GtkSorter$FUNC
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GtkSorter$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GtkSorter$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GtkSorter",
        constants$1903.glib_listautoptr_cleanup_GtkSorter$FUNC
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GtkSorter$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GtkSorter$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GtkSorter",
        constants$1903.glib_slistautoptr_cleanup_GtkSorter$FUNC
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GtkSorter$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GtkSorter$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GtkSorter",
        constants$1903.glib_queueautoptr_cleanup_GtkSorter$FUNC
    );
    static final FunctionDescriptor glib_autoptr_clear_GtkSorterClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GtkSorterClass$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GtkSorterClass",
        constants$1903.glib_autoptr_clear_GtkSorterClass$FUNC
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GtkSorterClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GtkSorterClass$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GtkSorterClass",
        constants$1903.glib_autoptr_cleanup_GtkSorterClass$FUNC
    );
}


