// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1783 {

    static final FunctionDescriptor gtk_app_chooser_widget_get_show_recommended$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_app_chooser_widget_get_show_recommended$MH = RuntimeHelper.downcallHandle(
        "gtk_app_chooser_widget_get_show_recommended",
        constants$1783.gtk_app_chooser_widget_get_show_recommended$FUNC
    );
    static final FunctionDescriptor gtk_app_chooser_widget_set_show_fallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_app_chooser_widget_set_show_fallback$MH = RuntimeHelper.downcallHandle(
        "gtk_app_chooser_widget_set_show_fallback",
        constants$1783.gtk_app_chooser_widget_set_show_fallback$FUNC
    );
    static final FunctionDescriptor gtk_app_chooser_widget_get_show_fallback$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_app_chooser_widget_get_show_fallback$MH = RuntimeHelper.downcallHandle(
        "gtk_app_chooser_widget_get_show_fallback",
        constants$1783.gtk_app_chooser_widget_get_show_fallback$FUNC
    );
    static final FunctionDescriptor gtk_app_chooser_widget_set_show_other$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_app_chooser_widget_set_show_other$MH = RuntimeHelper.downcallHandle(
        "gtk_app_chooser_widget_set_show_other",
        constants$1783.gtk_app_chooser_widget_set_show_other$FUNC
    );
    static final FunctionDescriptor gtk_app_chooser_widget_get_show_other$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_app_chooser_widget_get_show_other$MH = RuntimeHelper.downcallHandle(
        "gtk_app_chooser_widget_get_show_other",
        constants$1783.gtk_app_chooser_widget_get_show_other$FUNC
    );
    static final FunctionDescriptor gtk_app_chooser_widget_set_show_all$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_app_chooser_widget_set_show_all$MH = RuntimeHelper.downcallHandle(
        "gtk_app_chooser_widget_set_show_all",
        constants$1783.gtk_app_chooser_widget_set_show_all$FUNC
    );
}


