// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2279 {

    static final FunctionDescriptor gtk_print_context_set_cairo_context$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle gtk_print_context_set_cairo_context$MH = RuntimeHelper.downcallHandle(
        "gtk_print_context_set_cairo_context",
        constants$2279.gtk_print_context_set_cairo_context$FUNC
    );
    static final FunctionDescriptor GtkPrintSettingsFunc$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GtkPrintSettingsFunc$MH = RuntimeHelper.downcallHandle(
        constants$2279.GtkPrintSettingsFunc$FUNC
    );
    static final FunctionDescriptor gtk_print_settings_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_print_settings_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_print_settings_get_type",
        constants$2279.gtk_print_settings_get_type$FUNC
    );
    static final FunctionDescriptor gtk_print_settings_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle gtk_print_settings_new$MH = RuntimeHelper.downcallHandle(
        "gtk_print_settings_new",
        constants$2279.gtk_print_settings_new$FUNC
    );
    static final FunctionDescriptor gtk_print_settings_copy$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_print_settings_copy$MH = RuntimeHelper.downcallHandle(
        "gtk_print_settings_copy",
        constants$2279.gtk_print_settings_copy$FUNC
    );
}


