// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2614 {

    static final FunctionDescriptor glib_autoptr_clear_GtkTreeStore$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GtkTreeStore$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GtkTreeStore",
        constants$2614.glib_autoptr_clear_GtkTreeStore$FUNC
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GtkTreeStore$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GtkTreeStore$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GtkTreeStore",
        constants$2614.glib_autoptr_cleanup_GtkTreeStore$FUNC
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GtkTreeStore$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GtkTreeStore$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GtkTreeStore",
        constants$2614.glib_listautoptr_cleanup_GtkTreeStore$FUNC
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GtkTreeStore$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GtkTreeStore$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GtkTreeStore",
        constants$2614.glib_slistautoptr_cleanup_GtkTreeStore$FUNC
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GtkTreeStore$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GtkTreeStore$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GtkTreeStore",
        constants$2614.glib_queueautoptr_cleanup_GtkTreeStore$FUNC
    );
    static final FunctionDescriptor glib_autoptr_clear_GtkTreeView$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GtkTreeView$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GtkTreeView",
        constants$2614.glib_autoptr_clear_GtkTreeView$FUNC
    );
}


