// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2810 {

    static final FunctionDescriptor adw_spring_animation_set_clamp$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle adw_spring_animation_set_clamp$MH = RuntimeHelper.downcallHandle(
        "adw_spring_animation_set_clamp",
        constants$2810.adw_spring_animation_set_clamp$FUNC
    );
    static final FunctionDescriptor adw_spring_animation_get_estimated_duration$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle adw_spring_animation_get_estimated_duration$MH = RuntimeHelper.downcallHandle(
        "adw_spring_animation_get_estimated_duration",
        constants$2810.adw_spring_animation_get_estimated_duration$FUNC
    );
    static final FunctionDescriptor adw_spring_animation_get_velocity$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle adw_spring_animation_get_velocity$MH = RuntimeHelper.downcallHandle(
        "adw_spring_animation_get_velocity",
        constants$2810.adw_spring_animation_get_velocity$FUNC
    );
    static final FunctionDescriptor adw_squeezer_page_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle adw_squeezer_page_get_type$MH = RuntimeHelper.downcallHandle(
        "adw_squeezer_page_get_type",
        constants$2810.adw_squeezer_page_get_type$FUNC
    );
    static final FunctionDescriptor glib_autoptr_clear_AdwSqueezerPage$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_AdwSqueezerPage$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_AdwSqueezerPage",
        constants$2810.glib_autoptr_clear_AdwSqueezerPage$FUNC
    );
    static final FunctionDescriptor glib_autoptr_cleanup_AdwSqueezerPage$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_AdwSqueezerPage$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_AdwSqueezerPage",
        constants$2810.glib_autoptr_cleanup_AdwSqueezerPage$FUNC
    );
}


