// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1054 {

    static final FunctionDescriptor g_unix_mount_free$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_unix_mount_free$MH = RuntimeHelper.downcallHandle(
        "g_unix_mount_free",
        constants$1054.g_unix_mount_free$FUNC
    );
    static final FunctionDescriptor g_unix_mount_copy$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_unix_mount_copy$MH = RuntimeHelper.downcallHandle(
        "g_unix_mount_copy",
        constants$1054.g_unix_mount_copy$FUNC
    );
    static final FunctionDescriptor g_unix_mount_point_free$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_unix_mount_point_free$MH = RuntimeHelper.downcallHandle(
        "g_unix_mount_point_free",
        constants$1054.g_unix_mount_point_free$FUNC
    );
    static final FunctionDescriptor g_unix_mount_point_copy$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_unix_mount_point_copy$MH = RuntimeHelper.downcallHandle(
        "g_unix_mount_point_copy",
        constants$1054.g_unix_mount_point_copy$FUNC
    );
    static final FunctionDescriptor g_unix_mount_compare$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_unix_mount_compare$MH = RuntimeHelper.downcallHandle(
        "g_unix_mount_compare",
        constants$1054.g_unix_mount_compare$FUNC
    );
    static final FunctionDescriptor g_unix_mount_get_mount_path$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_unix_mount_get_mount_path$MH = RuntimeHelper.downcallHandle(
        "g_unix_mount_get_mount_path",
        constants$1054.g_unix_mount_get_mount_path$FUNC
    );
}


