// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1554 {

    static final FunctionDescriptor ynf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle ynf$MH = RuntimeHelper.downcallHandle(
        "ynf",
        constants$1554.ynf$FUNC
    );
    static final FunctionDescriptor __ynf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __ynf$MH = RuntimeHelper.downcallHandle(
        "__ynf",
        constants$1554.__ynf$FUNC
    );
    static final FunctionDescriptor erff$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle erff$MH = RuntimeHelper.downcallHandle(
        "erff",
        constants$1554.erff$FUNC
    );
    static final FunctionDescriptor __erff$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __erff$MH = RuntimeHelper.downcallHandle(
        "__erff",
        constants$1554.__erff$FUNC
    );
    static final FunctionDescriptor erfcf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle erfcf$MH = RuntimeHelper.downcallHandle(
        "erfcf",
        constants$1554.erfcf$FUNC
    );
    static final FunctionDescriptor __erfcf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __erfcf$MH = RuntimeHelper.downcallHandle(
        "__erfcf",
        constants$1554.__erfcf$FUNC
    );
}


