// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2680 {

    static final FunctionDescriptor glib_autoptr_cleanup_AdwActionRowClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_AdwActionRowClass$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_AdwActionRowClass",
        constants$2680.glib_autoptr_cleanup_AdwActionRowClass$FUNC
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_AdwActionRowClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_AdwActionRowClass$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_AdwActionRowClass",
        constants$2680.glib_listautoptr_cleanup_AdwActionRowClass$FUNC
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_AdwActionRowClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_AdwActionRowClass$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_AdwActionRowClass",
        constants$2680.glib_slistautoptr_cleanup_AdwActionRowClass$FUNC
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_AdwActionRowClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_AdwActionRowClass$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_AdwActionRowClass",
        constants$2680.glib_queueautoptr_cleanup_AdwActionRowClass$FUNC
    );
    static final FunctionDescriptor ADW_ACTION_ROW$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ADW_ACTION_ROW$MH = RuntimeHelper.downcallHandle(
        "ADW_ACTION_ROW",
        constants$2680.ADW_ACTION_ROW$FUNC
    );
    static final FunctionDescriptor ADW_ACTION_ROW_CLASS$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ADW_ACTION_ROW_CLASS$MH = RuntimeHelper.downcallHandle(
        "ADW_ACTION_ROW_CLASS",
        constants$2680.ADW_ACTION_ROW_CLASS$FUNC
    );
}


