// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2493 {

    static final FunctionDescriptor gtk_widget_paintable_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_widget_paintable_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_paintable_get_type",
        constants$2493.gtk_widget_paintable_get_type$FUNC
    );
    static final FunctionDescriptor glib_autoptr_clear_GtkWidgetPaintable$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GtkWidgetPaintable$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GtkWidgetPaintable",
        constants$2493.glib_autoptr_clear_GtkWidgetPaintable$FUNC
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GtkWidgetPaintable$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GtkWidgetPaintable$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GtkWidgetPaintable",
        constants$2493.glib_autoptr_cleanup_GtkWidgetPaintable$FUNC
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GtkWidgetPaintable$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GtkWidgetPaintable$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GtkWidgetPaintable",
        constants$2493.glib_listautoptr_cleanup_GtkWidgetPaintable$FUNC
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GtkWidgetPaintable$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GtkWidgetPaintable$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GtkWidgetPaintable",
        constants$2493.glib_slistautoptr_cleanup_GtkWidgetPaintable$FUNC
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GtkWidgetPaintable$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GtkWidgetPaintable$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GtkWidgetPaintable",
        constants$2493.glib_queueautoptr_cleanup_GtkWidgetPaintable$FUNC
    );
}


