// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2799 {

    static final FunctionDescriptor adw_preferences_window_close_subpage$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle adw_preferences_window_close_subpage$MH = RuntimeHelper.downcallHandle(
        "adw_preferences_window_close_subpage",
        constants$2799.adw_preferences_window_close_subpage$FUNC
    );
    static final FunctionDescriptor adw_preferences_window_add$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle adw_preferences_window_add$MH = RuntimeHelper.downcallHandle(
        "adw_preferences_window_add",
        constants$2799.adw_preferences_window_add$FUNC
    );
    static final FunctionDescriptor adw_preferences_window_remove$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle adw_preferences_window_remove$MH = RuntimeHelper.downcallHandle(
        "adw_preferences_window_remove",
        constants$2799.adw_preferences_window_remove$FUNC
    );
    static final FunctionDescriptor adw_preferences_window_get_visible_page$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle adw_preferences_window_get_visible_page$MH = RuntimeHelper.downcallHandle(
        "adw_preferences_window_get_visible_page",
        constants$2799.adw_preferences_window_get_visible_page$FUNC
    );
    static final FunctionDescriptor adw_preferences_window_set_visible_page$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle adw_preferences_window_set_visible_page$MH = RuntimeHelper.downcallHandle(
        "adw_preferences_window_set_visible_page",
        constants$2799.adw_preferences_window_set_visible_page$FUNC
    );
    static final FunctionDescriptor adw_preferences_window_get_visible_page_name$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle adw_preferences_window_get_visible_page_name$MH = RuntimeHelper.downcallHandle(
        "adw_preferences_window_get_visible_page_name",
        constants$2799.adw_preferences_window_get_visible_page_name$FUNC
    );
}


