// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1906 {

    static final FunctionDescriptor glib_autoptr_clear_GtkSortListModel$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GtkSortListModel$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GtkSortListModel",
        constants$1906.glib_autoptr_clear_GtkSortListModel$FUNC
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GtkSortListModel$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GtkSortListModel$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GtkSortListModel",
        constants$1906.glib_autoptr_cleanup_GtkSortListModel$FUNC
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GtkSortListModel$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GtkSortListModel$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GtkSortListModel",
        constants$1906.glib_listautoptr_cleanup_GtkSortListModel$FUNC
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GtkSortListModel$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GtkSortListModel$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GtkSortListModel",
        constants$1906.glib_slistautoptr_cleanup_GtkSortListModel$FUNC
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GtkSortListModel$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GtkSortListModel$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GtkSortListModel",
        constants$1906.glib_queueautoptr_cleanup_GtkSortListModel$FUNC
    );
    static final FunctionDescriptor glib_autoptr_clear_GtkSortListModelClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GtkSortListModelClass$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GtkSortListModelClass",
        constants$1906.glib_autoptr_clear_GtkSortListModelClass$FUNC
    );
}


