// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2185 {

    static final FunctionDescriptor gtk_lock_button_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_lock_button_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_lock_button_get_type",
        constants$2185.gtk_lock_button_get_type$FUNC
    );
    static final FunctionDescriptor gtk_lock_button_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_lock_button_new$MH = RuntimeHelper.downcallHandle(
        "gtk_lock_button_new",
        constants$2185.gtk_lock_button_new$FUNC
    );
    static final FunctionDescriptor gtk_lock_button_get_permission$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_lock_button_get_permission$MH = RuntimeHelper.downcallHandle(
        "gtk_lock_button_get_permission",
        constants$2185.gtk_lock_button_get_permission$FUNC
    );
    static final FunctionDescriptor gtk_lock_button_set_permission$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_lock_button_set_permission$MH = RuntimeHelper.downcallHandle(
        "gtk_lock_button_set_permission",
        constants$2185.gtk_lock_button_set_permission$FUNC
    );
    static final FunctionDescriptor gtk_init$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle gtk_init$MH = RuntimeHelper.downcallHandle(
        "gtk_init",
        constants$2185.gtk_init$FUNC
    );
    static final FunctionDescriptor gtk_init_check$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle gtk_init_check$MH = RuntimeHelper.downcallHandle(
        "gtk_init_check",
        constants$2185.gtk_init_check$FUNC
    );
}


