// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2006 {

    static final FunctionDescriptor gtk_accessible_tristate_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_accessible_tristate_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_accessible_tristate_get_type",
        constants$2006.gtk_accessible_tristate_get_type$FUNC
    );
    static final FunctionDescriptor gtk_accessible_invalid_state_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_accessible_invalid_state_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_accessible_invalid_state_get_type",
        constants$2006.gtk_accessible_invalid_state_get_type$FUNC
    );
    static final FunctionDescriptor gtk_accessible_autocomplete_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_accessible_autocomplete_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_accessible_autocomplete_get_type",
        constants$2006.gtk_accessible_autocomplete_get_type$FUNC
    );
    static final FunctionDescriptor gtk_accessible_sort_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_accessible_sort_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_accessible_sort_get_type",
        constants$2006.gtk_accessible_sort_get_type$FUNC
    );
    static final FunctionDescriptor gtk_event_controller_scroll_flags_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_event_controller_scroll_flags_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_event_controller_scroll_flags_get_type",
        constants$2006.gtk_event_controller_scroll_flags_get_type$FUNC
    );
    static final FunctionDescriptor gtk_file_chooser_action_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_file_chooser_action_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_file_chooser_action_get_type",
        constants$2006.gtk_file_chooser_action_get_type$FUNC
    );
}


