// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1833 {

    static final FunctionDescriptor glib_slistautoptr_cleanup_GtkBoxLayoutClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GtkBoxLayoutClass$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GtkBoxLayoutClass",
        constants$1833.glib_slistautoptr_cleanup_GtkBoxLayoutClass$FUNC
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GtkBoxLayoutClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GtkBoxLayoutClass$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GtkBoxLayoutClass",
        constants$1833.glib_queueautoptr_cleanup_GtkBoxLayoutClass$FUNC
    );
    static final FunctionDescriptor GTK_BOX_LAYOUT$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GTK_BOX_LAYOUT$MH = RuntimeHelper.downcallHandle(
        "GTK_BOX_LAYOUT",
        constants$1833.GTK_BOX_LAYOUT$FUNC
    );
    static final FunctionDescriptor GTK_IS_BOX_LAYOUT$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GTK_IS_BOX_LAYOUT$MH = RuntimeHelper.downcallHandle(
        "GTK_IS_BOX_LAYOUT",
        constants$1833.GTK_IS_BOX_LAYOUT$FUNC
    );
    static final FunctionDescriptor gtk_box_layout_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_box_layout_new$MH = RuntimeHelper.downcallHandle(
        "gtk_box_layout_new",
        constants$1833.gtk_box_layout_new$FUNC
    );
    static final FunctionDescriptor gtk_box_layout_set_homogeneous$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_box_layout_set_homogeneous$MH = RuntimeHelper.downcallHandle(
        "gtk_box_layout_set_homogeneous",
        constants$1833.gtk_box_layout_set_homogeneous$FUNC
    );
}


