// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1466 {

    static final FunctionDescriptor _mm_ucomile_ss$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _mm_ucomile_ss$MH = RuntimeHelper.downcallHandle(
        "_mm_ucomile_ss",
        constants$1466._mm_ucomile_ss$FUNC
    );
    static final FunctionDescriptor _mm_ucomigt_ss$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _mm_ucomigt_ss$MH = RuntimeHelper.downcallHandle(
        "_mm_ucomigt_ss",
        constants$1466._mm_ucomigt_ss$FUNC
    );
    static final FunctionDescriptor _mm_ucomige_ss$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _mm_ucomige_ss$MH = RuntimeHelper.downcallHandle(
        "_mm_ucomige_ss",
        constants$1466._mm_ucomige_ss$FUNC
    );
    static final FunctionDescriptor _mm_ucomineq_ss$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _mm_ucomineq_ss$MH = RuntimeHelper.downcallHandle(
        "_mm_ucomineq_ss",
        constants$1466._mm_ucomineq_ss$FUNC
    );
    static final FunctionDescriptor _mm_cvtss_si32$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _mm_cvtss_si32$MH = RuntimeHelper.downcallHandle(
        "_mm_cvtss_si32",
        constants$1466._mm_cvtss_si32$FUNC
    );
    static final FunctionDescriptor _mm_cvt_ss2si$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _mm_cvt_ss2si$MH = RuntimeHelper.downcallHandle(
        "_mm_cvt_ss2si",
        constants$1466._mm_cvt_ss2si$FUNC
    );
}


