// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2084 {

    static final FunctionDescriptor GTK_IS_FILTER_LIST_MODEL$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GTK_IS_FILTER_LIST_MODEL$MH = RuntimeHelper.downcallHandle(
        "GTK_IS_FILTER_LIST_MODEL",
        constants$2084.GTK_IS_FILTER_LIST_MODEL$FUNC
    );
    static final FunctionDescriptor gtk_filter_list_model_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_filter_list_model_new$MH = RuntimeHelper.downcallHandle(
        "gtk_filter_list_model_new",
        constants$2084.gtk_filter_list_model_new$FUNC
    );
    static final FunctionDescriptor gtk_filter_list_model_set_filter$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_filter_list_model_set_filter$MH = RuntimeHelper.downcallHandle(
        "gtk_filter_list_model_set_filter",
        constants$2084.gtk_filter_list_model_set_filter$FUNC
    );
    static final FunctionDescriptor gtk_filter_list_model_get_filter$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_filter_list_model_get_filter$MH = RuntimeHelper.downcallHandle(
        "gtk_filter_list_model_get_filter",
        constants$2084.gtk_filter_list_model_get_filter$FUNC
    );
    static final FunctionDescriptor gtk_filter_list_model_set_model$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_filter_list_model_set_model$MH = RuntimeHelper.downcallHandle(
        "gtk_filter_list_model_set_model",
        constants$2084.gtk_filter_list_model_set_model$FUNC
    );
    static final FunctionDescriptor gtk_filter_list_model_get_model$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_filter_list_model_get_model$MH = RuntimeHelper.downcallHandle(
        "gtk_filter_list_model_get_model",
        constants$2084.gtk_filter_list_model_get_model$FUNC
    );
}


