// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2032 {

    static final FunctionDescriptor glib_listautoptr_cleanup_GtkDirectoryListClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GtkDirectoryListClass$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GtkDirectoryListClass",
        constants$2032.glib_listautoptr_cleanup_GtkDirectoryListClass$FUNC
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GtkDirectoryListClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GtkDirectoryListClass$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GtkDirectoryListClass",
        constants$2032.glib_slistautoptr_cleanup_GtkDirectoryListClass$FUNC
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GtkDirectoryListClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GtkDirectoryListClass$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GtkDirectoryListClass",
        constants$2032.glib_queueautoptr_cleanup_GtkDirectoryListClass$FUNC
    );
    static final FunctionDescriptor GTK_DIRECTORY_LIST$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GTK_DIRECTORY_LIST$MH = RuntimeHelper.downcallHandle(
        "GTK_DIRECTORY_LIST",
        constants$2032.GTK_DIRECTORY_LIST$FUNC
    );
    static final FunctionDescriptor GTK_IS_DIRECTORY_LIST$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GTK_IS_DIRECTORY_LIST$MH = RuntimeHelper.downcallHandle(
        "GTK_IS_DIRECTORY_LIST",
        constants$2032.GTK_IS_DIRECTORY_LIST$FUNC
    );
    static final FunctionDescriptor gtk_directory_list_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_directory_list_new$MH = RuntimeHelper.downcallHandle(
        "gtk_directory_list_new",
        constants$2032.gtk_directory_list_new$FUNC
    );
}


