// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2091 {

    static final FunctionDescriptor gtk_flatten_list_model_get_model_for_item$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_flatten_list_model_get_model_for_item$MH = RuntimeHelper.downcallHandle(
        "gtk_flatten_list_model_get_model_for_item",
        constants$2091.gtk_flatten_list_model_get_model_for_item$FUNC
    );
    static final FunctionDescriptor GtkFlowBoxCreateWidgetFunc$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GtkFlowBoxCreateWidgetFunc$MH = RuntimeHelper.downcallHandle(
        constants$2091.GtkFlowBoxCreateWidgetFunc$FUNC
    );
    static final FunctionDescriptor gtk_flow_box_child_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_flow_box_child_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_flow_box_child_get_type",
        constants$2091.gtk_flow_box_child_get_type$FUNC
    );
    static final FunctionDescriptor gtk_flow_box_child_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle gtk_flow_box_child_new$MH = RuntimeHelper.downcallHandle(
        "gtk_flow_box_child_new",
        constants$2091.gtk_flow_box_child_new$FUNC
    );
    static final FunctionDescriptor gtk_flow_box_child_set_child$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_flow_box_child_set_child$MH = RuntimeHelper.downcallHandle(
        "gtk_flow_box_child_set_child",
        constants$2091.gtk_flow_box_child_set_child$FUNC
    );
}


