// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1679 {

    static final FunctionDescriptor gsk_transform_transform$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gsk_transform_transform$MH = RuntimeHelper.downcallHandle(
        "gsk_transform_transform",
        constants$1679.gsk_transform_transform$FUNC
    );
    static final FunctionDescriptor gsk_transform_invert$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gsk_transform_invert$MH = RuntimeHelper.downcallHandle(
        "gsk_transform_invert",
        constants$1679.gsk_transform_invert$FUNC
    );
    static final FunctionDescriptor gsk_transform_matrix$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gsk_transform_matrix$MH = RuntimeHelper.downcallHandle(
        "gsk_transform_matrix",
        constants$1679.gsk_transform_matrix$FUNC
    );
    static final FunctionDescriptor gsk_transform_translate$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gsk_transform_translate$MH = RuntimeHelper.downcallHandle(
        "gsk_transform_translate",
        constants$1679.gsk_transform_translate$FUNC
    );
    static final FunctionDescriptor gsk_transform_translate_3d$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gsk_transform_translate_3d$MH = RuntimeHelper.downcallHandle(
        "gsk_transform_translate_3d",
        constants$1679.gsk_transform_translate_3d$FUNC
    );
    static final FunctionDescriptor gsk_transform_skew$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle gsk_transform_skew$MH = RuntimeHelper.downcallHandle(
        "gsk_transform_skew",
        constants$1679.gsk_transform_skew$FUNC
    );
}


