// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2053 {

    static final FunctionDescriptor glib_queueautoptr_cleanup_GtkEditableLabel$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GtkEditableLabel$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GtkEditableLabel",
        constants$2053.glib_queueautoptr_cleanup_GtkEditableLabel$FUNC
    );
    static final FunctionDescriptor glib_autoptr_clear_GtkEditableLabelClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GtkEditableLabelClass$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GtkEditableLabelClass",
        constants$2053.glib_autoptr_clear_GtkEditableLabelClass$FUNC
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GtkEditableLabelClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GtkEditableLabelClass$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GtkEditableLabelClass",
        constants$2053.glib_autoptr_cleanup_GtkEditableLabelClass$FUNC
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GtkEditableLabelClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GtkEditableLabelClass$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GtkEditableLabelClass",
        constants$2053.glib_listautoptr_cleanup_GtkEditableLabelClass$FUNC
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GtkEditableLabelClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GtkEditableLabelClass$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GtkEditableLabelClass",
        constants$2053.glib_slistautoptr_cleanup_GtkEditableLabelClass$FUNC
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GtkEditableLabelClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GtkEditableLabelClass$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GtkEditableLabelClass",
        constants$2053.glib_queueautoptr_cleanup_GtkEditableLabelClass$FUNC
    );
}


