// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1676 {

    static final FunctionDescriptor gsk_renderer_unrealize$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gsk_renderer_unrealize$MH = RuntimeHelper.downcallHandle(
        "gsk_renderer_unrealize",
        constants$1676.gsk_renderer_unrealize$FUNC
    );
    static final FunctionDescriptor gsk_renderer_is_realized$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gsk_renderer_is_realized$MH = RuntimeHelper.downcallHandle(
        "gsk_renderer_is_realized",
        constants$1676.gsk_renderer_is_realized$FUNC
    );
    static final FunctionDescriptor gsk_renderer_render_texture$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gsk_renderer_render_texture$MH = RuntimeHelper.downcallHandle(
        "gsk_renderer_render_texture",
        constants$1676.gsk_renderer_render_texture$FUNC
    );
    static final FunctionDescriptor gsk_renderer_render$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gsk_renderer_render$MH = RuntimeHelper.downcallHandle(
        "gsk_renderer_render",
        constants$1676.gsk_renderer_render$FUNC
    );
    static final FunctionDescriptor gsk_transform_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gsk_transform_get_type$MH = RuntimeHelper.downcallHandle(
        "gsk_transform_get_type",
        constants$1676.gsk_transform_get_type$FUNC
    );
    static final FunctionDescriptor gsk_transform_ref$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gsk_transform_ref$MH = RuntimeHelper.downcallHandle(
        "gsk_transform_ref",
        constants$1676.gsk_transform_ref$FUNC
    );
}


