// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1355 {

    static final FunctionDescriptor gdk_content_formats_union_serialize_mime_types$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_content_formats_union_serialize_mime_types$MH = RuntimeHelper.downcallHandle(
        "gdk_content_formats_union_serialize_mime_types",
        constants$1355.gdk_content_formats_union_serialize_mime_types$FUNC
    );
    static final FunctionDescriptor gdk_content_register_serializer$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_content_register_serializer$MH = RuntimeHelper.downcallHandle(
        "gdk_content_register_serializer",
        constants$1355.gdk_content_register_serializer$FUNC
    );
    static final FunctionDescriptor gdk_content_serialize_async$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_content_serialize_async$MH = RuntimeHelper.downcallHandle(
        "gdk_content_serialize_async",
        constants$1355.gdk_content_serialize_async$FUNC
    );
    static final FunctionDescriptor gdk_content_serialize_finish$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_content_serialize_finish$MH = RuntimeHelper.downcallHandle(
        "gdk_content_serialize_finish",
        constants$1355.gdk_content_serialize_finish$FUNC
    );
    static final FunctionDescriptor gdk_cursor_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gdk_cursor_get_type$MH = RuntimeHelper.downcallHandle(
        "gdk_cursor_get_type",
        constants$1355.gdk_cursor_get_type$FUNC
    );
    static final FunctionDescriptor gdk_cursor_new_from_texture$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_cursor_new_from_texture$MH = RuntimeHelper.downcallHandle(
        "gdk_cursor_new_from_texture",
        constants$1355.gdk_cursor_new_from_texture$FUNC
    );
}


