// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1250 {

    static final FunctionDescriptor pango_font_map_changed$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_font_map_changed$MH = RuntimeHelper.downcallHandle(
        "pango_font_map_changed",
        constants$1250.pango_font_map_changed$FUNC
    );
    static final FunctionDescriptor pango_font_map_get_family$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_font_map_get_family$MH = RuntimeHelper.downcallHandle(
        "pango_font_map_get_family",
        constants$1250.pango_font_map_get_family$FUNC
    );
    static final FunctionDescriptor glib_autoptr_clear_PangoFontMap$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_PangoFontMap$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_PangoFontMap",
        constants$1250.glib_autoptr_clear_PangoFontMap$FUNC
    );
    static final FunctionDescriptor glib_autoptr_cleanup_PangoFontMap$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_PangoFontMap$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_PangoFontMap",
        constants$1250.glib_autoptr_cleanup_PangoFontMap$FUNC
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_PangoFontMap$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_PangoFontMap$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_PangoFontMap",
        constants$1250.glib_listautoptr_cleanup_PangoFontMap$FUNC
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_PangoFontMap$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_PangoFontMap$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_PangoFontMap",
        constants$1250.glib_slistautoptr_cleanup_PangoFontMap$FUNC
    );
}


