// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1339 {

    static final FunctionDescriptor gdk_cairo_context_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gdk_cairo_context_get_type$MH = RuntimeHelper.downcallHandle(
        "gdk_cairo_context_get_type",
        constants$1339.gdk_cairo_context_get_type$FUNC
    );
    static final FunctionDescriptor gdk_cairo_context_cairo_create$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_cairo_context_cairo_create$MH = RuntimeHelper.downcallHandle(
        "gdk_cairo_context_cairo_create",
        constants$1339.gdk_cairo_context_cairo_create$FUNC
    );
    static final FunctionDescriptor gdk_clipboard_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gdk_clipboard_get_type$MH = RuntimeHelper.downcallHandle(
        "gdk_clipboard_get_type",
        constants$1339.gdk_clipboard_get_type$FUNC
    );
    static final FunctionDescriptor gdk_clipboard_get_display$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_clipboard_get_display$MH = RuntimeHelper.downcallHandle(
        "gdk_clipboard_get_display",
        constants$1339.gdk_clipboard_get_display$FUNC
    );
    static final FunctionDescriptor gdk_clipboard_get_formats$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_clipboard_get_formats$MH = RuntimeHelper.downcallHandle(
        "gdk_clipboard_get_formats",
        constants$1339.gdk_clipboard_get_formats$FUNC
    );
    static final FunctionDescriptor gdk_clipboard_is_local$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_clipboard_is_local$MH = RuntimeHelper.downcallHandle(
        "gdk_clipboard_is_local",
        constants$1339.gdk_clipboard_is_local$FUNC
    );
}


