// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2676 {

    static final FunctionDescriptor glib_autoptr_clear_AdwPreferencesRowClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_AdwPreferencesRowClass$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_AdwPreferencesRowClass",
        constants$2676.glib_autoptr_clear_AdwPreferencesRowClass$FUNC
    );
    static final FunctionDescriptor glib_autoptr_cleanup_AdwPreferencesRowClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_AdwPreferencesRowClass$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_AdwPreferencesRowClass",
        constants$2676.glib_autoptr_cleanup_AdwPreferencesRowClass$FUNC
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_AdwPreferencesRowClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_AdwPreferencesRowClass$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_AdwPreferencesRowClass",
        constants$2676.glib_listautoptr_cleanup_AdwPreferencesRowClass$FUNC
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_AdwPreferencesRowClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_AdwPreferencesRowClass$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_AdwPreferencesRowClass",
        constants$2676.glib_slistautoptr_cleanup_AdwPreferencesRowClass$FUNC
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_AdwPreferencesRowClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_AdwPreferencesRowClass$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_AdwPreferencesRowClass",
        constants$2676.glib_queueautoptr_cleanup_AdwPreferencesRowClass$FUNC
    );
    static final FunctionDescriptor ADW_PREFERENCES_ROW$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ADW_PREFERENCES_ROW$MH = RuntimeHelper.downcallHandle(
        "ADW_PREFERENCES_ROW",
        constants$2676.ADW_PREFERENCES_ROW$FUNC
    );
}


