// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1678 {

    static final FunctionDescriptor gsk_transform_to_2d_components$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gsk_transform_to_2d_components$MH = RuntimeHelper.downcallHandle(
        "gsk_transform_to_2d_components",
        constants$1678.gsk_transform_to_2d_components$FUNC
    );
    static final FunctionDescriptor gsk_transform_to_affine$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gsk_transform_to_affine$MH = RuntimeHelper.downcallHandle(
        "gsk_transform_to_affine",
        constants$1678.gsk_transform_to_affine$FUNC
    );
    static final FunctionDescriptor gsk_transform_to_translate$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gsk_transform_to_translate$MH = RuntimeHelper.downcallHandle(
        "gsk_transform_to_translate",
        constants$1678.gsk_transform_to_translate$FUNC
    );
    static final FunctionDescriptor gsk_transform_get_category$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gsk_transform_get_category$MH = RuntimeHelper.downcallHandle(
        "gsk_transform_get_category",
        constants$1678.gsk_transform_get_category$FUNC
    );
    static final FunctionDescriptor gsk_transform_equal$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gsk_transform_equal$MH = RuntimeHelper.downcallHandle(
        "gsk_transform_equal",
        constants$1678.gsk_transform_equal$FUNC
    );
    static final FunctionDescriptor gsk_transform_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle gsk_transform_new$MH = RuntimeHelper.downcallHandle(
        "gsk_transform_new",
        constants$1678.gsk_transform_new$FUNC
    );
}


