// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1380 {

    static final FunctionDescriptor gdk_monitor_get_refresh_rate$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_monitor_get_refresh_rate$MH = RuntimeHelper.downcallHandle(
        "gdk_monitor_get_refresh_rate",
        constants$1380.gdk_monitor_get_refresh_rate$FUNC
    );
    static final FunctionDescriptor gdk_monitor_get_subpixel_layout$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_monitor_get_subpixel_layout$MH = RuntimeHelper.downcallHandle(
        "gdk_monitor_get_subpixel_layout",
        constants$1380.gdk_monitor_get_subpixel_layout$FUNC
    );
    static final FunctionDescriptor gdk_monitor_is_valid$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_monitor_is_valid$MH = RuntimeHelper.downcallHandle(
        "gdk_monitor_is_valid",
        constants$1380.gdk_monitor_is_valid$FUNC
    );
    static final FunctionDescriptor gdk_popup_layout_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gdk_popup_layout_get_type$MH = RuntimeHelper.downcallHandle(
        "gdk_popup_layout_get_type",
        constants$1380.gdk_popup_layout_get_type$FUNC
    );
    static final FunctionDescriptor gdk_popup_layout_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gdk_popup_layout_new$MH = RuntimeHelper.downcallHandle(
        "gdk_popup_layout_new",
        constants$1380.gdk_popup_layout_new$FUNC
    );
    static final FunctionDescriptor gdk_popup_layout_ref$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_popup_layout_ref$MH = RuntimeHelper.downcallHandle(
        "gdk_popup_layout_ref",
        constants$1380.gdk_popup_layout_ref$FUNC
    );
}


