// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2882 {

    static final MemorySegment G_DIR_SEPARATOR_S$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("/");
    static final MemorySegment G_SEARCHPATH_SEPARATOR_S$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String(":");
    static final MemorySegment G_OS_INFO_KEY_NAME$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("NAME");
    static final MemorySegment G_OS_INFO_KEY_PRETTY_NAME$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("PRETTY_NAME");
    static final MemorySegment G_OS_INFO_KEY_VERSION$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("VERSION");
    static final MemorySegment G_OS_INFO_KEY_VERSION_CODENAME$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("VERSION_CODENAME");
}


