// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1112 {

    static final FunctionDescriptor cairo_surface_create_observer$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle cairo_surface_create_observer$MH = RuntimeHelper.downcallHandle(
        "cairo_surface_create_observer",
        constants$1112.cairo_surface_create_observer$FUNC
    );
    static final FunctionDescriptor cairo_surface_observer_callback_t$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle cairo_surface_observer_callback_t$MH = RuntimeHelper.downcallHandle(
        constants$1112.cairo_surface_observer_callback_t$FUNC
    );
    static final FunctionDescriptor cairo_surface_observer_add_paint_callback$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle cairo_surface_observer_add_paint_callback$MH = RuntimeHelper.downcallHandle(
        "cairo_surface_observer_add_paint_callback",
        constants$1112.cairo_surface_observer_add_paint_callback$FUNC
    );
    static final FunctionDescriptor cairo_surface_observer_add_mask_callback$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle cairo_surface_observer_add_mask_callback$MH = RuntimeHelper.downcallHandle(
        "cairo_surface_observer_add_mask_callback",
        constants$1112.cairo_surface_observer_add_mask_callback$FUNC
    );
    static final FunctionDescriptor cairo_surface_observer_add_fill_callback$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle cairo_surface_observer_add_fill_callback$MH = RuntimeHelper.downcallHandle(
        "cairo_surface_observer_add_fill_callback",
        constants$1112.cairo_surface_observer_add_fill_callback$FUNC
    );
}


