// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2435 {

    static final FunctionDescriptor gtk_text_buffer_get_line_count$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_text_buffer_get_line_count$MH = RuntimeHelper.downcallHandle(
        "gtk_text_buffer_get_line_count",
        constants$2435.gtk_text_buffer_get_line_count$FUNC
    );
    static final FunctionDescriptor gtk_text_buffer_get_char_count$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_text_buffer_get_char_count$MH = RuntimeHelper.downcallHandle(
        "gtk_text_buffer_get_char_count",
        constants$2435.gtk_text_buffer_get_char_count$FUNC
    );
    static final FunctionDescriptor gtk_text_buffer_get_tag_table$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_text_buffer_get_tag_table$MH = RuntimeHelper.downcallHandle(
        "gtk_text_buffer_get_tag_table",
        constants$2435.gtk_text_buffer_get_tag_table$FUNC
    );
    static final FunctionDescriptor gtk_text_buffer_set_text$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_text_buffer_set_text$MH = RuntimeHelper.downcallHandle(
        "gtk_text_buffer_set_text",
        constants$2435.gtk_text_buffer_set_text$FUNC
    );
    static final FunctionDescriptor gtk_text_buffer_insert$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_text_buffer_insert$MH = RuntimeHelper.downcallHandle(
        "gtk_text_buffer_insert",
        constants$2435.gtk_text_buffer_insert$FUNC
    );
    static final FunctionDescriptor gtk_text_buffer_insert_at_cursor$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_text_buffer_insert_at_cursor$MH = RuntimeHelper.downcallHandle(
        "gtk_text_buffer_insert_at_cursor",
        constants$2435.gtk_text_buffer_insert_at_cursor$FUNC
    );
}


