// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1726 {

    static final FunctionDescriptor gtk_widget_set_size_request$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_widget_set_size_request$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_set_size_request",
        constants$1726.gtk_widget_set_size_request$FUNC
    );
    static final FunctionDescriptor gtk_widget_get_size_request$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_get_size_request$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_get_size_request",
        constants$1726.gtk_widget_get_size_request$FUNC
    );
    static final FunctionDescriptor gtk_widget_set_opacity$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle gtk_widget_set_opacity$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_set_opacity",
        constants$1726.gtk_widget_set_opacity$FUNC
    );
    static final FunctionDescriptor gtk_widget_get_opacity$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_get_opacity$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_get_opacity",
        constants$1726.gtk_widget_get_opacity$FUNC
    );
    static final FunctionDescriptor gtk_widget_set_overflow$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_widget_set_overflow$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_set_overflow",
        constants$1726.gtk_widget_set_overflow$FUNC
    );
    static final FunctionDescriptor gtk_widget_get_overflow$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_get_overflow$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_get_overflow",
        constants$1726.gtk_widget_get_overflow$FUNC
    );
}


