// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$990 {

    static final FunctionDescriptor g_desktop_app_info_get_nodisplay$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_desktop_app_info_get_nodisplay$MH = RuntimeHelper.downcallHandle(
        "g_desktop_app_info_get_nodisplay",
        constants$990.g_desktop_app_info_get_nodisplay$FUNC
    );
    static final FunctionDescriptor g_desktop_app_info_get_show_in$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_desktop_app_info_get_show_in$MH = RuntimeHelper.downcallHandle(
        "g_desktop_app_info_get_show_in",
        constants$990.g_desktop_app_info_get_show_in$FUNC
    );
    static final FunctionDescriptor g_desktop_app_info_get_startup_wm_class$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_desktop_app_info_get_startup_wm_class$MH = RuntimeHelper.downcallHandle(
        "g_desktop_app_info_get_startup_wm_class",
        constants$990.g_desktop_app_info_get_startup_wm_class$FUNC
    );
    static final FunctionDescriptor g_desktop_app_info_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_desktop_app_info_new$MH = RuntimeHelper.downcallHandle(
        "g_desktop_app_info_new",
        constants$990.g_desktop_app_info_new$FUNC
    );
    static final FunctionDescriptor g_desktop_app_info_get_is_hidden$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_desktop_app_info_get_is_hidden$MH = RuntimeHelper.downcallHandle(
        "g_desktop_app_info_get_is_hidden",
        constants$990.g_desktop_app_info_get_is_hidden$FUNC
    );
    static final FunctionDescriptor g_desktop_app_info_set_desktop_env$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_desktop_app_info_set_desktop_env$MH = RuntimeHelper.downcallHandle(
        "g_desktop_app_info_set_desktop_env",
        constants$990.g_desktop_app_info_set_desktop_env$FUNC
    );
}


