// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1882 {

    static final FunctionDescriptor gtk_cell_layout_pack_start$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_cell_layout_pack_start$MH = RuntimeHelper.downcallHandle(
        "gtk_cell_layout_pack_start",
        constants$1882.gtk_cell_layout_pack_start$FUNC
    );
    static final FunctionDescriptor gtk_cell_layout_pack_end$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_cell_layout_pack_end$MH = RuntimeHelper.downcallHandle(
        "gtk_cell_layout_pack_end",
        constants$1882.gtk_cell_layout_pack_end$FUNC
    );
    static final FunctionDescriptor gtk_cell_layout_get_cells$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_cell_layout_get_cells$MH = RuntimeHelper.downcallHandle(
        "gtk_cell_layout_get_cells",
        constants$1882.gtk_cell_layout_get_cells$FUNC
    );
    static final FunctionDescriptor gtk_cell_layout_clear$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_cell_layout_clear$MH = RuntimeHelper.downcallHandle(
        "gtk_cell_layout_clear",
        constants$1882.gtk_cell_layout_clear$FUNC
    );
    static final FunctionDescriptor gtk_cell_layout_set_attributes$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_cell_layout_set_attributes$MH = RuntimeHelper.downcallHandleVariadic(
        "gtk_cell_layout_set_attributes",
        constants$1882.gtk_cell_layout_set_attributes$FUNC
    );
    static final FunctionDescriptor gtk_cell_layout_add_attribute$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_cell_layout_add_attribute$MH = RuntimeHelper.downcallHandle(
        "gtk_cell_layout_add_attribute",
        constants$1882.gtk_cell_layout_add_attribute$FUNC
    );
}


