// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$993 {

    static final FunctionDescriptor g_desktop_app_info_launch_uris_as_manager$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_desktop_app_info_launch_uris_as_manager$MH = RuntimeHelper.downcallHandle(
        "g_desktop_app_info_launch_uris_as_manager",
        constants$993.g_desktop_app_info_launch_uris_as_manager$FUNC
    );
    static final FunctionDescriptor g_desktop_app_info_launch_uris_as_manager_with_fds$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_desktop_app_info_launch_uris_as_manager_with_fds$MH = RuntimeHelper.downcallHandle(
        "g_desktop_app_info_launch_uris_as_manager_with_fds",
        constants$993.g_desktop_app_info_launch_uris_as_manager_with_fds$FUNC
    );
    static final FunctionDescriptor g_desktop_app_info_search$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_desktop_app_info_search$MH = RuntimeHelper.downcallHandle(
        "g_desktop_app_info_search",
        constants$993.g_desktop_app_info_search$FUNC
    );
    static final FunctionDescriptor g_desktop_app_info_get_implementations$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_desktop_app_info_get_implementations$MH = RuntimeHelper.downcallHandle(
        "g_desktop_app_info_get_implementations",
        constants$993.g_desktop_app_info_get_implementations$FUNC
    );
    static final FunctionDescriptor glib_autoptr_clear_GFileDescriptorBased$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GFileDescriptorBased$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GFileDescriptorBased",
        constants$993.glib_autoptr_clear_GFileDescriptorBased$FUNC
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GFileDescriptorBased$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GFileDescriptorBased$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GFileDescriptorBased",
        constants$993.glib_autoptr_cleanup_GFileDescriptorBased$FUNC
    );
}


