// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1453 {

    static final FunctionDescriptor _mm_srl_si64$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _mm_srl_si64$MH = RuntimeHelper.downcallHandle(
        "_mm_srl_si64",
        constants$1453._mm_srl_si64$FUNC
    );
    static final FunctionDescriptor _mm_srli_si64$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle _mm_srli_si64$MH = RuntimeHelper.downcallHandle(
        "_mm_srli_si64",
        constants$1453._mm_srli_si64$FUNC
    );
    static final FunctionDescriptor _mm_and_si64$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _mm_and_si64$MH = RuntimeHelper.downcallHandle(
        "_mm_and_si64",
        constants$1453._mm_and_si64$FUNC
    );
    static final FunctionDescriptor _mm_andnot_si64$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _mm_andnot_si64$MH = RuntimeHelper.downcallHandle(
        "_mm_andnot_si64",
        constants$1453._mm_andnot_si64$FUNC
    );
    static final FunctionDescriptor _mm_or_si64$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _mm_or_si64$MH = RuntimeHelper.downcallHandle(
        "_mm_or_si64",
        constants$1453._mm_or_si64$FUNC
    );
    static final FunctionDescriptor _mm_xor_si64$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _mm_xor_si64$MH = RuntimeHelper.downcallHandle(
        "_mm_xor_si64",
        constants$1453._mm_xor_si64$FUNC
    );
}


