// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2236 {

    static final FunctionDescriptor gtk_notebook_prepend_page$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_notebook_prepend_page$MH = RuntimeHelper.downcallHandle(
        "gtk_notebook_prepend_page",
        constants$2236.gtk_notebook_prepend_page$FUNC
    );
    static final FunctionDescriptor gtk_notebook_prepend_page_menu$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_notebook_prepend_page_menu$MH = RuntimeHelper.downcallHandle(
        "gtk_notebook_prepend_page_menu",
        constants$2236.gtk_notebook_prepend_page_menu$FUNC
    );
    static final FunctionDescriptor gtk_notebook_insert_page$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_notebook_insert_page$MH = RuntimeHelper.downcallHandle(
        "gtk_notebook_insert_page",
        constants$2236.gtk_notebook_insert_page$FUNC
    );
    static final FunctionDescriptor gtk_notebook_insert_page_menu$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_notebook_insert_page_menu$MH = RuntimeHelper.downcallHandle(
        "gtk_notebook_insert_page_menu",
        constants$2236.gtk_notebook_insert_page_menu$FUNC
    );
    static final FunctionDescriptor gtk_notebook_remove_page$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_notebook_remove_page$MH = RuntimeHelper.downcallHandle(
        "gtk_notebook_remove_page",
        constants$2236.gtk_notebook_remove_page$FUNC
    );
    static final FunctionDescriptor gtk_notebook_set_group_name$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_notebook_set_group_name$MH = RuntimeHelper.downcallHandle(
        "gtk_notebook_set_group_name",
        constants$2236.gtk_notebook_set_group_name$FUNC
    );
}


