// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1597 {

    static final FunctionDescriptor graphene_matrix_is_2d$FUNC = FunctionDescriptor.of(Constants$root.C_BOOL$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_matrix_is_2d$MH = RuntimeHelper.downcallHandle(
        "graphene_matrix_is_2d",
        constants$1597.graphene_matrix_is_2d$FUNC
    );
    static final FunctionDescriptor graphene_matrix_is_backface_visible$FUNC = FunctionDescriptor.of(Constants$root.C_BOOL$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_matrix_is_backface_visible$MH = RuntimeHelper.downcallHandle(
        "graphene_matrix_is_backface_visible",
        constants$1597.graphene_matrix_is_backface_visible$FUNC
    );
    static final FunctionDescriptor graphene_matrix_is_singular$FUNC = FunctionDescriptor.of(Constants$root.C_BOOL$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_matrix_is_singular$MH = RuntimeHelper.downcallHandle(
        "graphene_matrix_is_singular",
        constants$1597.graphene_matrix_is_singular$FUNC
    );
    static final FunctionDescriptor graphene_matrix_to_float$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_matrix_to_float$MH = RuntimeHelper.downcallHandle(
        "graphene_matrix_to_float",
        constants$1597.graphene_matrix_to_float$FUNC
    );
    static final FunctionDescriptor graphene_matrix_to_2d$FUNC = FunctionDescriptor.of(Constants$root.C_BOOL$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_matrix_to_2d$MH = RuntimeHelper.downcallHandle(
        "graphene_matrix_to_2d",
        constants$1597.graphene_matrix_to_2d$FUNC
    );
    static final FunctionDescriptor graphene_matrix_get_row$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle graphene_matrix_get_row$MH = RuntimeHelper.downcallHandle(
        "graphene_matrix_get_row",
        constants$1597.graphene_matrix_get_row$FUNC
    );
}


