// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2730 {

    static final FunctionDescriptor adw_carousel_indicator_lines_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle adw_carousel_indicator_lines_new$MH = RuntimeHelper.downcallHandle(
        "adw_carousel_indicator_lines_new",
        constants$2730.adw_carousel_indicator_lines_new$FUNC
    );
    static final FunctionDescriptor adw_carousel_indicator_lines_get_carousel$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle adw_carousel_indicator_lines_get_carousel$MH = RuntimeHelper.downcallHandle(
        "adw_carousel_indicator_lines_get_carousel",
        constants$2730.adw_carousel_indicator_lines_get_carousel$FUNC
    );
    static final FunctionDescriptor adw_carousel_indicator_lines_set_carousel$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle adw_carousel_indicator_lines_set_carousel$MH = RuntimeHelper.downcallHandle(
        "adw_carousel_indicator_lines_set_carousel",
        constants$2730.adw_carousel_indicator_lines_set_carousel$FUNC
    );
    static final FunctionDescriptor adw_clamp_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle adw_clamp_get_type$MH = RuntimeHelper.downcallHandle(
        "adw_clamp_get_type",
        constants$2730.adw_clamp_get_type$FUNC
    );
    static final FunctionDescriptor glib_autoptr_clear_AdwClamp$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_AdwClamp$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_AdwClamp",
        constants$2730.glib_autoptr_clear_AdwClamp$FUNC
    );
    static final FunctionDescriptor glib_autoptr_cleanup_AdwClamp$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_AdwClamp$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_AdwClamp",
        constants$2730.glib_autoptr_cleanup_AdwClamp$FUNC
    );
}


