// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2031 {

    static final FunctionDescriptor glib_autoptr_cleanup_GtkDirectoryList$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GtkDirectoryList$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GtkDirectoryList",
        constants$2031.glib_autoptr_cleanup_GtkDirectoryList$FUNC
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GtkDirectoryList$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GtkDirectoryList$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GtkDirectoryList",
        constants$2031.glib_listautoptr_cleanup_GtkDirectoryList$FUNC
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GtkDirectoryList$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GtkDirectoryList$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GtkDirectoryList",
        constants$2031.glib_slistautoptr_cleanup_GtkDirectoryList$FUNC
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GtkDirectoryList$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GtkDirectoryList$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GtkDirectoryList",
        constants$2031.glib_queueautoptr_cleanup_GtkDirectoryList$FUNC
    );
    static final FunctionDescriptor glib_autoptr_clear_GtkDirectoryListClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GtkDirectoryListClass$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GtkDirectoryListClass",
        constants$2031.glib_autoptr_clear_GtkDirectoryListClass$FUNC
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GtkDirectoryListClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GtkDirectoryListClass$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GtkDirectoryListClass",
        constants$2031.glib_autoptr_cleanup_GtkDirectoryListClass$FUNC
    );
}


