// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2359 {

    static final FunctionDescriptor glib_autoptr_cleanup_GtkSingleSelectionClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GtkSingleSelectionClass$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GtkSingleSelectionClass",
        constants$2359.glib_autoptr_cleanup_GtkSingleSelectionClass$FUNC
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GtkSingleSelectionClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GtkSingleSelectionClass$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GtkSingleSelectionClass",
        constants$2359.glib_listautoptr_cleanup_GtkSingleSelectionClass$FUNC
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GtkSingleSelectionClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GtkSingleSelectionClass$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GtkSingleSelectionClass",
        constants$2359.glib_slistautoptr_cleanup_GtkSingleSelectionClass$FUNC
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GtkSingleSelectionClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GtkSingleSelectionClass$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GtkSingleSelectionClass",
        constants$2359.glib_queueautoptr_cleanup_GtkSingleSelectionClass$FUNC
    );
    static final FunctionDescriptor GTK_SINGLE_SELECTION$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GTK_SINGLE_SELECTION$MH = RuntimeHelper.downcallHandle(
        "GTK_SINGLE_SELECTION",
        constants$2359.GTK_SINGLE_SELECTION$FUNC
    );
    static final FunctionDescriptor GTK_IS_SINGLE_SELECTION$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GTK_IS_SINGLE_SELECTION$MH = RuntimeHelper.downcallHandle(
        "GTK_IS_SINGLE_SELECTION",
        constants$2359.GTK_IS_SINGLE_SELECTION$FUNC
    );
}


