// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1401 {

    static final FunctionDescriptor gdk_drop_finish$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gdk_drop_finish$MH = RuntimeHelper.downcallHandle(
        "gdk_drop_finish",
        constants$1401.gdk_drop_finish$FUNC
    );
    static final FunctionDescriptor gdk_drop_read_async$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_drop_read_async$MH = RuntimeHelper.downcallHandle(
        "gdk_drop_read_async",
        constants$1401.gdk_drop_read_async$FUNC
    );
    static final FunctionDescriptor gdk_drop_read_finish$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_drop_read_finish$MH = RuntimeHelper.downcallHandle(
        "gdk_drop_read_finish",
        constants$1401.gdk_drop_read_finish$FUNC
    );
    static final FunctionDescriptor gdk_drop_read_value_async$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_drop_read_value_async$MH = RuntimeHelper.downcallHandle(
        "gdk_drop_read_value_async",
        constants$1401.gdk_drop_read_value_async$FUNC
    );
    static final FunctionDescriptor gdk_drop_read_value_finish$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_drop_read_value_finish$MH = RuntimeHelper.downcallHandle(
        "gdk_drop_read_value_finish",
        constants$1401.gdk_drop_read_value_finish$FUNC
    );
    static final FunctionDescriptor gdk_input_source_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gdk_input_source_get_type$MH = RuntimeHelper.downcallHandle(
        "gdk_input_source_get_type",
        constants$1401.gdk_input_source_get_type$FUNC
    );
}


