// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2632 {

    static final FunctionDescriptor gtk_print_job_set_page_set$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_print_job_set_page_set$MH = RuntimeHelper.downcallHandle(
        "gtk_print_job_set_page_set",
        constants$2632.gtk_print_job_set_page_set$FUNC
    );
    static final FunctionDescriptor gtk_print_job_get_num_copies$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_print_job_get_num_copies$MH = RuntimeHelper.downcallHandle(
        "gtk_print_job_get_num_copies",
        constants$2632.gtk_print_job_get_num_copies$FUNC
    );
    static final FunctionDescriptor gtk_print_job_set_num_copies$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_print_job_set_num_copies$MH = RuntimeHelper.downcallHandle(
        "gtk_print_job_set_num_copies",
        constants$2632.gtk_print_job_set_num_copies$FUNC
    );
    static final FunctionDescriptor gtk_print_job_get_scale$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_print_job_get_scale$MH = RuntimeHelper.downcallHandle(
        "gtk_print_job_get_scale",
        constants$2632.gtk_print_job_get_scale$FUNC
    );
    static final FunctionDescriptor gtk_print_job_set_scale$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle gtk_print_job_set_scale$MH = RuntimeHelper.downcallHandle(
        "gtk_print_job_set_scale",
        constants$2632.gtk_print_job_set_scale$FUNC
    );
    static final FunctionDescriptor gtk_print_job_get_n_up$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_print_job_get_n_up$MH = RuntimeHelper.downcallHandle(
        "gtk_print_job_get_n_up",
        constants$2632.gtk_print_job_get_n_up$FUNC
    );
}


