// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1761 {

    static final FunctionDescriptor glib_listautoptr_cleanup_GtkWindowGroup$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GtkWindowGroup$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GtkWindowGroup",
        constants$1761.glib_listautoptr_cleanup_GtkWindowGroup$FUNC
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GtkWindowGroup$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GtkWindowGroup$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GtkWindowGroup",
        constants$1761.glib_slistautoptr_cleanup_GtkWindowGroup$FUNC
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GtkWindowGroup$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GtkWindowGroup$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GtkWindowGroup",
        constants$1761.glib_queueautoptr_cleanup_GtkWindowGroup$FUNC
    );
    static final FunctionDescriptor gtk_about_dialog_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_about_dialog_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_about_dialog_get_type",
        constants$1761.gtk_about_dialog_get_type$FUNC
    );
    static final FunctionDescriptor gtk_about_dialog_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle gtk_about_dialog_new$MH = RuntimeHelper.downcallHandle(
        "gtk_about_dialog_new",
        constants$1761.gtk_about_dialog_new$FUNC
    );
    static final FunctionDescriptor gtk_show_about_dialog$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_show_about_dialog$MH = RuntimeHelper.downcallHandleVariadic(
        "gtk_show_about_dialog",
        constants$1761.gtk_show_about_dialog$FUNC
    );
}


