// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1508 {

    static final FunctionDescriptor _mm_setzero_si128$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle _mm_setzero_si128$MH = RuntimeHelper.downcallHandle(
        "_mm_setzero_si128",
        constants$1508._mm_setzero_si128$FUNC
    );
    static final FunctionDescriptor _mm_store_si128$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _mm_store_si128$MH = RuntimeHelper.downcallHandle(
        "_mm_store_si128",
        constants$1508._mm_store_si128$FUNC
    );
    static final FunctionDescriptor _mm_storeu_si128$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _mm_storeu_si128$MH = RuntimeHelper.downcallHandle(
        "_mm_storeu_si128",
        constants$1508._mm_storeu_si128$FUNC
    );
    static final FunctionDescriptor _mm_storeu_si64$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _mm_storeu_si64$MH = RuntimeHelper.downcallHandle(
        "_mm_storeu_si64",
        constants$1508._mm_storeu_si64$FUNC
    );
    static final FunctionDescriptor _mm_storeu_si32$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _mm_storeu_si32$MH = RuntimeHelper.downcallHandle(
        "_mm_storeu_si32",
        constants$1508._mm_storeu_si32$FUNC
    );
    static final FunctionDescriptor _mm_storeu_si16$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _mm_storeu_si16$MH = RuntimeHelper.downcallHandle(
        "_mm_storeu_si16",
        constants$1508._mm_storeu_si16$FUNC
    );
}


