// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2388 {

    static final FunctionDescriptor gtk_stack_switcher_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle gtk_stack_switcher_new$MH = RuntimeHelper.downcallHandle(
        "gtk_stack_switcher_new",
        constants$2388.gtk_stack_switcher_new$FUNC
    );
    static final FunctionDescriptor gtk_stack_switcher_set_stack$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_stack_switcher_set_stack$MH = RuntimeHelper.downcallHandle(
        "gtk_stack_switcher_set_stack",
        constants$2388.gtk_stack_switcher_set_stack$FUNC
    );
    static final FunctionDescriptor gtk_stack_switcher_get_stack$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_stack_switcher_get_stack$MH = RuntimeHelper.downcallHandle(
        "gtk_stack_switcher_get_stack",
        constants$2388.gtk_stack_switcher_get_stack$FUNC
    );
    static final FunctionDescriptor gtk_statusbar_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_statusbar_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_statusbar_get_type",
        constants$2388.gtk_statusbar_get_type$FUNC
    );
    static final FunctionDescriptor gtk_statusbar_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle gtk_statusbar_new$MH = RuntimeHelper.downcallHandle(
        "gtk_statusbar_new",
        constants$2388.gtk_statusbar_new$FUNC
    );
    static final FunctionDescriptor gtk_statusbar_get_context_id$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_statusbar_get_context_id$MH = RuntimeHelper.downcallHandle(
        "gtk_statusbar_get_context_id",
        constants$2388.gtk_statusbar_get_context_id$FUNC
    );
}


