// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2830 {

    static final FunctionDescriptor glib_listautoptr_cleanup_AdwTabPage$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_AdwTabPage$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_AdwTabPage",
        constants$2830.glib_listautoptr_cleanup_AdwTabPage$FUNC
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_AdwTabPage$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_AdwTabPage$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_AdwTabPage",
        constants$2830.glib_slistautoptr_cleanup_AdwTabPage$FUNC
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_AdwTabPage$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_AdwTabPage$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_AdwTabPage",
        constants$2830.glib_queueautoptr_cleanup_AdwTabPage$FUNC
    );
    static final FunctionDescriptor glib_autoptr_clear_AdwTabPageClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_AdwTabPageClass$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_AdwTabPageClass",
        constants$2830.glib_autoptr_clear_AdwTabPageClass$FUNC
    );
    static final FunctionDescriptor glib_autoptr_cleanup_AdwTabPageClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_AdwTabPageClass$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_AdwTabPageClass",
        constants$2830.glib_autoptr_cleanup_AdwTabPageClass$FUNC
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_AdwTabPageClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_AdwTabPageClass$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_AdwTabPageClass",
        constants$2830.glib_listautoptr_cleanup_AdwTabPageClass$FUNC
    );
}


