// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1475 {

    static final FunctionDescriptor _mm_sad_pu8$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _mm_sad_pu8$MH = RuntimeHelper.downcallHandle(
        "_mm_sad_pu8",
        constants$1475._mm_sad_pu8$FUNC
    );
    static final FunctionDescriptor _mm_getcsr$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle _mm_getcsr$MH = RuntimeHelper.downcallHandle(
        "_mm_getcsr",
        constants$1475._mm_getcsr$FUNC
    );
    static final FunctionDescriptor _mm_setcsr$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle _mm_setcsr$MH = RuntimeHelper.downcallHandle(
        "_mm_setcsr",
        constants$1475._mm_setcsr$FUNC
    );
    static final FunctionDescriptor _mm_unpackhi_ps$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _mm_unpackhi_ps$MH = RuntimeHelper.downcallHandle(
        "_mm_unpackhi_ps",
        constants$1475._mm_unpackhi_ps$FUNC
    );
    static final FunctionDescriptor _mm_unpacklo_ps$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _mm_unpacklo_ps$MH = RuntimeHelper.downcallHandle(
        "_mm_unpacklo_ps",
        constants$1475._mm_unpacklo_ps$FUNC
    );
    static final FunctionDescriptor _mm_move_ss$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _mm_move_ss$MH = RuntimeHelper.downcallHandle(
        "_mm_move_ss",
        constants$1475._mm_move_ss$FUNC
    );
}


