// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2695 {

    static final FunctionDescriptor adw_animation_get_state$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle adw_animation_get_state$MH = RuntimeHelper.downcallHandle(
        "adw_animation_get_state",
        constants$2695.adw_animation_get_state$FUNC
    );
    static final FunctionDescriptor adw_animation_play$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle adw_animation_play$MH = RuntimeHelper.downcallHandle(
        "adw_animation_play",
        constants$2695.adw_animation_play$FUNC
    );
    static final FunctionDescriptor adw_animation_pause$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle adw_animation_pause$MH = RuntimeHelper.downcallHandle(
        "adw_animation_pause",
        constants$2695.adw_animation_pause$FUNC
    );
    static final FunctionDescriptor adw_animation_resume$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle adw_animation_resume$MH = RuntimeHelper.downcallHandle(
        "adw_animation_resume",
        constants$2695.adw_animation_resume$FUNC
    );
    static final FunctionDescriptor adw_animation_reset$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle adw_animation_reset$MH = RuntimeHelper.downcallHandle(
        "adw_animation_reset",
        constants$2695.adw_animation_reset$FUNC
    );
    static final FunctionDescriptor adw_animation_skip$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle adw_animation_skip$MH = RuntimeHelper.downcallHandle(
        "adw_animation_skip",
        constants$2695.adw_animation_skip$FUNC
    );
}


