// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1541 {

    static final FunctionDescriptor __atan2f$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __atan2f$MH = RuntimeHelper.downcallHandle(
        "__atan2f",
        constants$1541.__atan2f$FUNC
    );
    static final FunctionDescriptor cosf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle cosf$MH = RuntimeHelper.downcallHandle(
        "cosf",
        constants$1541.cosf$FUNC
    );
    static final FunctionDescriptor __cosf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __cosf$MH = RuntimeHelper.downcallHandle(
        "__cosf",
        constants$1541.__cosf$FUNC
    );
    static final FunctionDescriptor sinf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle sinf$MH = RuntimeHelper.downcallHandle(
        "sinf",
        constants$1541.sinf$FUNC
    );
    static final FunctionDescriptor __sinf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __sinf$MH = RuntimeHelper.downcallHandle(
        "__sinf",
        constants$1541.__sinf$FUNC
    );
    static final FunctionDescriptor tanf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle tanf$MH = RuntimeHelper.downcallHandle(
        "tanf",
        constants$1541.tanf$FUNC
    );
}


