// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2294 {

    static final FunctionDescriptor gtk_print_operation_get_print_settings$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_print_operation_get_print_settings$MH = RuntimeHelper.downcallHandle(
        "gtk_print_operation_get_print_settings",
        constants$2294.gtk_print_operation_get_print_settings$FUNC
    );
    static final FunctionDescriptor gtk_print_operation_set_job_name$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_print_operation_set_job_name$MH = RuntimeHelper.downcallHandle(
        "gtk_print_operation_set_job_name",
        constants$2294.gtk_print_operation_set_job_name$FUNC
    );
    static final FunctionDescriptor gtk_print_operation_set_n_pages$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_print_operation_set_n_pages$MH = RuntimeHelper.downcallHandle(
        "gtk_print_operation_set_n_pages",
        constants$2294.gtk_print_operation_set_n_pages$FUNC
    );
    static final FunctionDescriptor gtk_print_operation_set_current_page$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_print_operation_set_current_page$MH = RuntimeHelper.downcallHandle(
        "gtk_print_operation_set_current_page",
        constants$2294.gtk_print_operation_set_current_page$FUNC
    );
    static final FunctionDescriptor gtk_print_operation_set_use_full_page$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_print_operation_set_use_full_page$MH = RuntimeHelper.downcallHandle(
        "gtk_print_operation_set_use_full_page",
        constants$2294.gtk_print_operation_set_use_full_page$FUNC
    );
    static final FunctionDescriptor gtk_print_operation_set_unit$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_print_operation_set_unit$MH = RuntimeHelper.downcallHandle(
        "gtk_print_operation_set_unit",
        constants$2294.gtk_print_operation_set_unit$FUNC
    );
}


