// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2494 {

    static final FunctionDescriptor glib_autoptr_clear_GtkWidgetPaintableClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GtkWidgetPaintableClass$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GtkWidgetPaintableClass",
        constants$2494.glib_autoptr_clear_GtkWidgetPaintableClass$FUNC
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GtkWidgetPaintableClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GtkWidgetPaintableClass$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GtkWidgetPaintableClass",
        constants$2494.glib_autoptr_cleanup_GtkWidgetPaintableClass$FUNC
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GtkWidgetPaintableClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GtkWidgetPaintableClass$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GtkWidgetPaintableClass",
        constants$2494.glib_listautoptr_cleanup_GtkWidgetPaintableClass$FUNC
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GtkWidgetPaintableClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GtkWidgetPaintableClass$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GtkWidgetPaintableClass",
        constants$2494.glib_slistautoptr_cleanup_GtkWidgetPaintableClass$FUNC
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GtkWidgetPaintableClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GtkWidgetPaintableClass$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GtkWidgetPaintableClass",
        constants$2494.glib_queueautoptr_cleanup_GtkWidgetPaintableClass$FUNC
    );
    static final FunctionDescriptor GTK_WIDGET_PAINTABLE$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GTK_WIDGET_PAINTABLE$MH = RuntimeHelper.downcallHandle(
        "GTK_WIDGET_PAINTABLE",
        constants$2494.GTK_WIDGET_PAINTABLE$FUNC
    );
}


