// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2398 {

    static final FunctionDescriptor gtk_string_list_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_string_list_new$MH = RuntimeHelper.downcallHandle(
        "gtk_string_list_new",
        constants$2398.gtk_string_list_new$FUNC
    );
    static final FunctionDescriptor gtk_string_list_append$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_string_list_append$MH = RuntimeHelper.downcallHandle(
        "gtk_string_list_append",
        constants$2398.gtk_string_list_append$FUNC
    );
    static final FunctionDescriptor gtk_string_list_take$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_string_list_take$MH = RuntimeHelper.downcallHandle(
        "gtk_string_list_take",
        constants$2398.gtk_string_list_take$FUNC
    );
    static final FunctionDescriptor gtk_string_list_remove$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_string_list_remove$MH = RuntimeHelper.downcallHandle(
        "gtk_string_list_remove",
        constants$2398.gtk_string_list_remove$FUNC
    );
    static final FunctionDescriptor gtk_string_list_splice$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_string_list_splice$MH = RuntimeHelper.downcallHandle(
        "gtk_string_list_splice",
        constants$2398.gtk_string_list_splice$FUNC
    );
    static final FunctionDescriptor gtk_string_list_get_string$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_string_list_get_string$MH = RuntimeHelper.downcallHandle(
        "gtk_string_list_get_string",
        constants$2398.gtk_string_list_get_string$FUNC
    );
}


