// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1942 {

    static final FunctionDescriptor gtk_list_store_remove$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_list_store_remove$MH = RuntimeHelper.downcallHandle(
        "gtk_list_store_remove",
        constants$1942.gtk_list_store_remove$FUNC
    );
    static final FunctionDescriptor gtk_list_store_insert$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_list_store_insert$MH = RuntimeHelper.downcallHandle(
        "gtk_list_store_insert",
        constants$1942.gtk_list_store_insert$FUNC
    );
    static final FunctionDescriptor gtk_list_store_insert_before$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_list_store_insert_before$MH = RuntimeHelper.downcallHandle(
        "gtk_list_store_insert_before",
        constants$1942.gtk_list_store_insert_before$FUNC
    );
    static final FunctionDescriptor gtk_list_store_insert_after$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_list_store_insert_after$MH = RuntimeHelper.downcallHandle(
        "gtk_list_store_insert_after",
        constants$1942.gtk_list_store_insert_after$FUNC
    );
    static final FunctionDescriptor gtk_list_store_insert_with_values$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_list_store_insert_with_values$MH = RuntimeHelper.downcallHandleVariadic(
        "gtk_list_store_insert_with_values",
        constants$1942.gtk_list_store_insert_with_values$FUNC
    );
    static final FunctionDescriptor gtk_list_store_insert_with_valuesv$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_list_store_insert_with_valuesv$MH = RuntimeHelper.downcallHandle(
        "gtk_list_store_insert_with_valuesv",
        constants$1942.gtk_list_store_insert_with_valuesv$FUNC
    );
}


