// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2028 {

    static final FunctionDescriptor glib_autoptr_clear_GtkCustomSorter$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GtkCustomSorter$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GtkCustomSorter",
        constants$2028.glib_autoptr_clear_GtkCustomSorter$FUNC
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GtkCustomSorter$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GtkCustomSorter$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GtkCustomSorter",
        constants$2028.glib_autoptr_cleanup_GtkCustomSorter$FUNC
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GtkCustomSorter$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GtkCustomSorter$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GtkCustomSorter",
        constants$2028.glib_listautoptr_cleanup_GtkCustomSorter$FUNC
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GtkCustomSorter$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GtkCustomSorter$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GtkCustomSorter",
        constants$2028.glib_slistautoptr_cleanup_GtkCustomSorter$FUNC
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GtkCustomSorter$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GtkCustomSorter$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GtkCustomSorter",
        constants$2028.glib_queueautoptr_cleanup_GtkCustomSorter$FUNC
    );
    static final FunctionDescriptor glib_autoptr_clear_GtkCustomSorterClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GtkCustomSorterClass$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GtkCustomSorterClass",
        constants$2028.glib_autoptr_clear_GtkCustomSorterClass$FUNC
    );
}


