// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1343 {

    static final FunctionDescriptor GdkContentDeserializeFunc$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GdkContentDeserializeFunc$MH = RuntimeHelper.downcallHandle(
        constants$1343.GdkContentDeserializeFunc$FUNC
    );
    static final FunctionDescriptor gdk_content_deserializer_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gdk_content_deserializer_get_type$MH = RuntimeHelper.downcallHandle(
        "gdk_content_deserializer_get_type",
        constants$1343.gdk_content_deserializer_get_type$FUNC
    );
    static final FunctionDescriptor gdk_content_deserializer_get_mime_type$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_content_deserializer_get_mime_type$MH = RuntimeHelper.downcallHandle(
        "gdk_content_deserializer_get_mime_type",
        constants$1343.gdk_content_deserializer_get_mime_type$FUNC
    );
    static final FunctionDescriptor gdk_content_deserializer_get_gtype$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_content_deserializer_get_gtype$MH = RuntimeHelper.downcallHandle(
        "gdk_content_deserializer_get_gtype",
        constants$1343.gdk_content_deserializer_get_gtype$FUNC
    );
    static final FunctionDescriptor gdk_content_deserializer_get_value$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_content_deserializer_get_value$MH = RuntimeHelper.downcallHandle(
        "gdk_content_deserializer_get_value",
        constants$1343.gdk_content_deserializer_get_value$FUNC
    );
    static final FunctionDescriptor gdk_content_deserializer_get_input_stream$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_content_deserializer_get_input_stream$MH = RuntimeHelper.downcallHandle(
        "gdk_content_deserializer_get_input_stream",
        constants$1343.gdk_content_deserializer_get_input_stream$FUNC
    );
}


