// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2220 {

    static final FunctionDescriptor glib_queueautoptr_cleanup_GtkAnyFilter$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GtkAnyFilter$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GtkAnyFilter",
        constants$2220.glib_queueautoptr_cleanup_GtkAnyFilter$FUNC
    );
    static final FunctionDescriptor glib_autoptr_clear_GtkAnyFilterClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GtkAnyFilterClass$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GtkAnyFilterClass",
        constants$2220.glib_autoptr_clear_GtkAnyFilterClass$FUNC
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GtkAnyFilterClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GtkAnyFilterClass$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GtkAnyFilterClass",
        constants$2220.glib_autoptr_cleanup_GtkAnyFilterClass$FUNC
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GtkAnyFilterClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GtkAnyFilterClass$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GtkAnyFilterClass",
        constants$2220.glib_listautoptr_cleanup_GtkAnyFilterClass$FUNC
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GtkAnyFilterClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GtkAnyFilterClass$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GtkAnyFilterClass",
        constants$2220.glib_slistautoptr_cleanup_GtkAnyFilterClass$FUNC
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GtkAnyFilterClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GtkAnyFilterClass$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GtkAnyFilterClass",
        constants$2220.glib_queueautoptr_cleanup_GtkAnyFilterClass$FUNC
    );
}


