// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2866 {

    static final FunctionDescriptor glib_autoptr_clear_AdwViewSwitcherClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_AdwViewSwitcherClass$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_AdwViewSwitcherClass",
        constants$2866.glib_autoptr_clear_AdwViewSwitcherClass$FUNC
    );
    static final FunctionDescriptor glib_autoptr_cleanup_AdwViewSwitcherClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_AdwViewSwitcherClass$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_AdwViewSwitcherClass",
        constants$2866.glib_autoptr_cleanup_AdwViewSwitcherClass$FUNC
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_AdwViewSwitcherClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_AdwViewSwitcherClass$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_AdwViewSwitcherClass",
        constants$2866.glib_listautoptr_cleanup_AdwViewSwitcherClass$FUNC
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_AdwViewSwitcherClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_AdwViewSwitcherClass$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_AdwViewSwitcherClass",
        constants$2866.glib_slistautoptr_cleanup_AdwViewSwitcherClass$FUNC
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_AdwViewSwitcherClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_AdwViewSwitcherClass$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_AdwViewSwitcherClass",
        constants$2866.glib_queueautoptr_cleanup_AdwViewSwitcherClass$FUNC
    );
    static final FunctionDescriptor ADW_VIEW_SWITCHER$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ADW_VIEW_SWITCHER$MH = RuntimeHelper.downcallHandle(
        "ADW_VIEW_SWITCHER",
        constants$2866.ADW_VIEW_SWITCHER$FUNC
    );
}


