// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2117 {

    static final FunctionDescriptor gtk_gl_area_set_use_es$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_gl_area_set_use_es$MH = RuntimeHelper.downcallHandle(
        "gtk_gl_area_set_use_es",
        constants$2117.gtk_gl_area_set_use_es$FUNC
    );
    static final FunctionDescriptor gtk_gl_area_get_use_es$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_gl_area_get_use_es$MH = RuntimeHelper.downcallHandle(
        "gtk_gl_area_get_use_es",
        constants$2117.gtk_gl_area_get_use_es$FUNC
    );
    static final FunctionDescriptor gtk_gl_area_set_required_version$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_gl_area_set_required_version$MH = RuntimeHelper.downcallHandle(
        "gtk_gl_area_set_required_version",
        constants$2117.gtk_gl_area_set_required_version$FUNC
    );
    static final FunctionDescriptor gtk_gl_area_get_required_version$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_gl_area_get_required_version$MH = RuntimeHelper.downcallHandle(
        "gtk_gl_area_get_required_version",
        constants$2117.gtk_gl_area_get_required_version$FUNC
    );
    static final FunctionDescriptor gtk_gl_area_get_has_depth_buffer$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_gl_area_get_has_depth_buffer$MH = RuntimeHelper.downcallHandle(
        "gtk_gl_area_get_has_depth_buffer",
        constants$2117.gtk_gl_area_get_has_depth_buffer$FUNC
    );
    static final FunctionDescriptor gtk_gl_area_set_has_depth_buffer$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_gl_area_set_has_depth_buffer$MH = RuntimeHelper.downcallHandle(
        "gtk_gl_area_set_has_depth_buffer",
        constants$2117.gtk_gl_area_set_has_depth_buffer$FUNC
    );
}


