// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1516 {

    static final FunctionDescriptor __acos$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __acos$MH = RuntimeHelper.downcallHandle(
        "__acos",
        constants$1516.__acos$FUNC
    );
    static final FunctionDescriptor asin$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle asin$MH = RuntimeHelper.downcallHandle(
        "asin",
        constants$1516.asin$FUNC
    );
    static final FunctionDescriptor __asin$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __asin$MH = RuntimeHelper.downcallHandle(
        "__asin",
        constants$1516.__asin$FUNC
    );
    static final FunctionDescriptor atan$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle atan$MH = RuntimeHelper.downcallHandle(
        "atan",
        constants$1516.atan$FUNC
    );
    static final FunctionDescriptor __atan$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __atan$MH = RuntimeHelper.downcallHandle(
        "__atan",
        constants$1516.__atan$FUNC
    );
    static final FunctionDescriptor atan2$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle atan2$MH = RuntimeHelper.downcallHandle(
        "atan2",
        constants$1516.atan2$FUNC
    );
}


