// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2422 {

    static final FunctionDescriptor gtk_text_iter_editable$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_text_iter_editable$MH = RuntimeHelper.downcallHandle(
        "gtk_text_iter_editable",
        constants$2422.gtk_text_iter_editable$FUNC
    );
    static final FunctionDescriptor gtk_text_iter_can_insert$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_text_iter_can_insert$MH = RuntimeHelper.downcallHandle(
        "gtk_text_iter_can_insert",
        constants$2422.gtk_text_iter_can_insert$FUNC
    );
    static final FunctionDescriptor gtk_text_iter_starts_word$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_text_iter_starts_word$MH = RuntimeHelper.downcallHandle(
        "gtk_text_iter_starts_word",
        constants$2422.gtk_text_iter_starts_word$FUNC
    );
    static final FunctionDescriptor gtk_text_iter_ends_word$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_text_iter_ends_word$MH = RuntimeHelper.downcallHandle(
        "gtk_text_iter_ends_word",
        constants$2422.gtk_text_iter_ends_word$FUNC
    );
    static final FunctionDescriptor gtk_text_iter_inside_word$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_text_iter_inside_word$MH = RuntimeHelper.downcallHandle(
        "gtk_text_iter_inside_word",
        constants$2422.gtk_text_iter_inside_word$FUNC
    );
    static final FunctionDescriptor gtk_text_iter_starts_sentence$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_text_iter_starts_sentence$MH = RuntimeHelper.downcallHandle(
        "gtk_text_iter_starts_sentence",
        constants$2422.gtk_text_iter_starts_sentence$FUNC
    );
}


