// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public interface GdkPixbufModuleSaveFunc {

    int apply(java.lang.foreign.MemoryAddress f, java.lang.foreign.MemoryAddress pixbuf, java.lang.foreign.MemoryAddress param_keys, java.lang.foreign.MemoryAddress param_values, java.lang.foreign.MemoryAddress error);
    static MemorySegment allocate(GdkPixbufModuleSaveFunc fi, MemorySession session) {
        return RuntimeHelper.upcallStub(GdkPixbufModuleSaveFunc.class, fi, constants$1320.GdkPixbufModuleSaveFunc$FUNC, session);
    }
    static GdkPixbufModuleSaveFunc ofAddress(MemoryAddress addr, MemorySession session) {
        MemorySegment symbol = MemorySegment.ofAddress(addr, 0, session);
        return (java.lang.foreign.MemoryAddress _f, java.lang.foreign.MemoryAddress _pixbuf, java.lang.foreign.MemoryAddress _param_keys, java.lang.foreign.MemoryAddress _param_values, java.lang.foreign.MemoryAddress _error) -> {
            try {
                return (int)constants$1320.GdkPixbufModuleSaveFunc$MH.invokeExact((Addressable)symbol, (java.lang.foreign.Addressable)_f, (java.lang.foreign.Addressable)_pixbuf, (java.lang.foreign.Addressable)_param_keys, (java.lang.foreign.Addressable)_param_values, (java.lang.foreign.Addressable)_error);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


