// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class sockaddr_un {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_SHORT$LAYOUT.withName("sun_family"),
        MemoryLayout.sequenceLayout(108, Constants$root.C_CHAR$LAYOUT).withName("sun_path")
    ).withName("sockaddr_un");
    public static MemoryLayout $LAYOUT() {
        return sockaddr_un.$struct$LAYOUT;
    }
    static final VarHandle sun_family$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("sun_family"));
    public static VarHandle sun_family$VH() {
        return sockaddr_un.sun_family$VH;
    }
    public static short sun_family$get(MemorySegment seg) {
        return (short)sockaddr_un.sun_family$VH.get(seg);
    }
    public static void sun_family$set( MemorySegment seg, short x) {
        sockaddr_un.sun_family$VH.set(seg, x);
    }
    public static short sun_family$get(MemorySegment seg, long index) {
        return (short)sockaddr_un.sun_family$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void sun_family$set(MemorySegment seg, long index, short x) {
        sockaddr_un.sun_family$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment sun_path$slice(MemorySegment seg) {
        return seg.asSlice(2, 108);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


