// Generated by jextract

package io.github.jwharm.javagi.interop.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class tcp_zerocopy_receive {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG_LONG$LAYOUT.withName("address"),
        Constants$root.C_INT$LAYOUT.withName("length"),
        Constants$root.C_INT$LAYOUT.withName("recv_skip_hint")
    ).withName("tcp_zerocopy_receive");
    public static MemoryLayout $LAYOUT() {
        return tcp_zerocopy_receive.$struct$LAYOUT;
    }
    static final VarHandle address$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("address"));
    public static VarHandle address$VH() {
        return tcp_zerocopy_receive.address$VH;
    }
    public static long address$get(MemorySegment seg) {
        return (long)tcp_zerocopy_receive.address$VH.get(seg);
    }
    public static void address$set( MemorySegment seg, long x) {
        tcp_zerocopy_receive.address$VH.set(seg, x);
    }
    public static long address$get(MemorySegment seg, long index) {
        return (long)tcp_zerocopy_receive.address$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void address$set(MemorySegment seg, long index, long x) {
        tcp_zerocopy_receive.address$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle length$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("length"));
    public static VarHandle length$VH() {
        return tcp_zerocopy_receive.length$VH;
    }
    public static int length$get(MemorySegment seg) {
        return (int)tcp_zerocopy_receive.length$VH.get(seg);
    }
    public static void length$set( MemorySegment seg, int x) {
        tcp_zerocopy_receive.length$VH.set(seg, x);
    }
    public static int length$get(MemorySegment seg, long index) {
        return (int)tcp_zerocopy_receive.length$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void length$set(MemorySegment seg, long index, int x) {
        tcp_zerocopy_receive.length$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle recv_skip_hint$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("recv_skip_hint"));
    public static VarHandle recv_skip_hint$VH() {
        return tcp_zerocopy_receive.recv_skip_hint$VH;
    }
    public static int recv_skip_hint$get(MemorySegment seg) {
        return (int)tcp_zerocopy_receive.recv_skip_hint$VH.get(seg);
    }
    public static void recv_skip_hint$set( MemorySegment seg, int x) {
        tcp_zerocopy_receive.recv_skip_hint$VH.set(seg, x);
    }
    public static int recv_skip_hint$get(MemorySegment seg, long index) {
        return (int)tcp_zerocopy_receive.recv_skip_hint$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void recv_skip_hint$set(MemorySegment seg, long index, int x) {
        tcp_zerocopy_receive.recv_skip_hint$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


