package org.gtk.gdk;

import org.gtk.gobject.*;
import io.github.jwharm.javagi.interop.*;
import jdk.incubator.foreign.*;
import java.lang.invoke.*;

/**
 * `GdkEvent`s are immutable data structures, created by GDK to
 * represent windowing system events.
 * 
 * In GTK applications the events are handled automatically by toplevel
 * widgets and passed on to the event controllers of appropriate widgets,
 * so using `GdkEvent` and its related API is rarely needed.
 */
public class Event extends org.gtk.gobject.Object {

    public Event(io.github.jwharm.javagi.interop.Proxy proxy) {
        super(proxy);
    }
    
    /** Cast object to Event */
    public static Event castFrom(org.gtk.gobject.Object gobject) {
        return new Event(gobject.getProxy());
    }
    
    /**
     * Returns the device of an event.
     */
    public Device getDevice() {
        var RESULT = io.github.jwharm.javagi.interop.jextract.gtk_h.gdk_event_get_device(HANDLE());
        return new Device(ProxyFactory.getProxy(RESULT, false));
    }
    
    /**
     * Returns a `GdkDeviceTool` representing the tool that
     * caused the event.
     * 
     * If the was not generated by a device that supports
     * different tools (such as a tablet), this function will
     * return %NULL.
     * 
     * Note: the `GdkDeviceTool` will be constant during
     * the application lifetime, if settings must be stored
     * persistently across runs, see [method@Gdk.DeviceTool.get_serial].
     */
    public DeviceTool getDeviceTool() {
        var RESULT = io.github.jwharm.javagi.interop.jextract.gtk_h.gdk_event_get_device_tool(HANDLE());
        return new DeviceTool(ProxyFactory.getProxy(RESULT, false));
    }
    
    /**
     * Retrieves the display associated to the @event.
     */
    public Display getDisplay() {
        var RESULT = io.github.jwharm.javagi.interop.jextract.gtk_h.gdk_event_get_display(HANDLE());
        return new Display(ProxyFactory.getProxy(RESULT, false));
    }
    
    /**
     * Retuns the event sequence to which the event belongs.
     * 
     * Related touch events are connected in a sequence. Other
     * events typically don't have event sequence information.
     */
    public EventSequence getEventSequence() {
        var RESULT = io.github.jwharm.javagi.interop.jextract.gtk_h.gdk_event_get_event_sequence(HANDLE());
        return new EventSequence(ProxyFactory.getProxy(RESULT, false));
    }
    
    /**
     * Retrieves the type of the event.
     */
    public EventType getEventType() {
        var RESULT = io.github.jwharm.javagi.interop.jextract.gtk_h.gdk_event_get_event_type(HANDLE());
        return EventType.fromValue(RESULT);
    }
    
    /**
     * Returns the modifier state field of an event.
     */
    public int getModifierState() {
        var RESULT = io.github.jwharm.javagi.interop.jextract.gtk_h.gdk_event_get_modifier_state(HANDLE());
        return RESULT;
    }
    
    /**
     * Returns whether this event is an 'emulated' pointer event.
     * 
     * Emulated pointer events typically originate from a touch events.
     */
    public boolean getPointerEmulated() {
        var RESULT = io.github.jwharm.javagi.interop.jextract.gtk_h.gdk_event_get_pointer_emulated(HANDLE());
        return (RESULT != 0);
    }
    
    /**
     * Returns the seat that originated the event.
     */
    public Seat getSeat() {
        var RESULT = io.github.jwharm.javagi.interop.jextract.gtk_h.gdk_event_get_seat(HANDLE());
        return new Seat(ProxyFactory.getProxy(RESULT, false));
    }
    
    /**
     * Extracts the surface associated with an event.
     */
    public Surface getSurface() {
        var RESULT = io.github.jwharm.javagi.interop.jextract.gtk_h.gdk_event_get_surface(HANDLE());
        return new Surface(ProxyFactory.getProxy(RESULT, false));
    }
    
    /**
     * Returns the timestamp of @event.
     * 
     * Not all events have timestamps. In that case, this function
     * returns %GDK_CURRENT_TIME.
     */
    public int getTime() {
        var RESULT = io.github.jwharm.javagi.interop.jextract.gtk_h.gdk_event_get_time(HANDLE());
        return RESULT;
    }
    
    /**
     * Increase the ref count of @event.
     */
    public Event ref() {
        var RESULT = io.github.jwharm.javagi.interop.jextract.gtk_h.gdk_event_ref(HANDLE());
        return new Event(ProxyFactory.getProxy(RESULT, true));
    }
    
    /**
     * Returns whether a `GdkEvent` should trigger a context menu,
     * according to platform conventions.
     * 
     * The right mouse button typically triggers context menus.
     * 
     * This function should always be used instead of simply checking for
     * event->button == %GDK_BUTTON_SECONDARY.
     */
    public boolean triggersContextMenu() {
        var RESULT = io.github.jwharm.javagi.interop.jextract.gtk_h.gdk_event_triggers_context_menu(HANDLE());
        return (RESULT != 0);
    }
    
    /**
     * Decrease the ref count of @event.
     * 
     * If the last reference is dropped, the structure is freed.
     */
    public void unref() {
        io.github.jwharm.javagi.interop.jextract.gtk_h.gdk_event_unref(HANDLE());
    }
    
}
